<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Administrador_glyphicons glyphicons-exit</name>
   <tag></tag>
   <elementGuidId>005c8438-4716-4f36-8e2e-5035a3429246</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.glyphicons.glyphicons-exit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f51593a-d812-4629-aaa1-7b2961c321c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>001535d5-ba5e-4f77-8e63-d31c7d5c4d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Salir</value>
      <webElementGuid>8e8d523a-bac4-427d-8762-2e400e40f810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.jsfcljs(document.getElementById('j_idt44'),{'j_idt44:j_idt51':'j_idt44:j_idt51'},'');return false</value>
      <webElementGuid>13ac8e36-a2eb-42be-b122-eb1cec50106e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-exit</value>
      <webElementGuid>acab8e23-2d45-4ef4-9e61-14a831371dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opcionSalir&quot;)/table[@class=&quot;us-icono-menu&quot;]/tbody[1]/tr[1]/td[3]/a[@class=&quot;glyphicons glyphicons-exit&quot;]</value>
      <webElementGuid>e07a21d2-afd2-4816-90b1-4d2e11bba4ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f553cb0-6560-423b-a21d-195c93f300cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>19ccd59b-481f-49be-a459-c63b4f04ca78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Salir</value>
      <webElementGuid>82f232b8-114c-4383-84c2-7fcf59eccbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.jsfcljs(document.getElementById('j_idt44'),{'j_idt44:j_idt51':'j_idt44:j_idt51'},'');return false</value>
      <webElementGuid>aa3fada1-4466-41b6-8ab6-a79d55f96b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-exit</value>
      <webElementGuid>062bfcce-b7c5-4e26-8526-b61e6e84a618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opcionSalir&quot;)/table[@class=&quot;us-icono-menu&quot;]/tbody[1]/tr[1]/td[3]/a[@class=&quot;glyphicons glyphicons-exit&quot;]</value>
      <webElementGuid>f909f7c1-5eef-4606-bd6d-ed1e187054b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;mojarra.jsfcljs(document.getElementById('j_idt44'),{'j_idt44:j_idt51':'j_idt44:j_idt51'},'');return false&quot;]</value>
      <webElementGuid>e77c1e8b-2e7e-4ab4-accb-4e27522868c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opcionSalir']/table/tbody/tr/td[3]/a</value>
      <webElementGuid>16307607-1168-4f1c-8009-b7820f85ee2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>8ac53552-d264-482f-9c61-1764dde1aacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>c9620473-c437-4b55-b57b-9cd95f5fdd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Salir']</value>
      <webElementGuid>fb4f38de-661d-42b2-a835-7cc2834a5e56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
