<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Empresa 1_cerrar_menu</name>
   <tag></tag>
   <elementGuidId>f8dcc22e-2c24-4ef0-803d-7ecd18be950d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cerrar_menu</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d3db2387-a275-41b5-aeac-d2fbf9919873</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cerrar_menu</value>
      <webElementGuid>cfc80e16-ec3f-4c41-aa64-540938c0d5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-chevron-right us-cl-primario us-boton-menu movimiento</value>
      <webElementGuid>1f76fa5a-df5c-4e74-b1c8-31ddfa04464d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cerrar_menu&quot;)</value>
      <webElementGuid>c0d72561-ddd2-443e-96aa-b596f1361ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32ecb94c-fcc2-4740-b0da-2bda2bc3a84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cerrar_menu</value>
      <webElementGuid>24b8b4eb-ffea-4cd8-b6d2-99aa9002246f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-chevron-right us-cl-primario us-boton-menu movimiento</value>
      <webElementGuid>1eaef365-2adb-45bd-883c-2bbf9dee0aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cerrar_menu&quot;)</value>
      <webElementGuid>273655c2-31bd-42f9-9bac-c4b6ded309c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='cerrar_menu']</value>
      <webElementGuid>4c649815-562f-4fdd-8ab1-2e8662193215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='j_idt44']/div/a</value>
      <webElementGuid>183dfc3c-1cd3-4aea-93a4-c845dd91ba5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/a</value>
      <webElementGuid>53ae71bc-ac51-430a-9c1b-237c6c1b1d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'cerrar_menu']</value>
      <webElementGuid>59ef4b56-a527-4775-bc89-98a965aa3fde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
