<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Actualizar</name>
   <tag></tag>
   <elementGuidId>4c2a782a-4588-4cd2-93a8-a9b00df7e8c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Actualizar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d5fefecf-3be2-43e0-80cd-dd3c8f111e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_parametroformato:tabInfo:j_idt315</value>
      <webElementGuid>4d1dd1b8-47b6-48bf-9df9-38151bf74446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>c5ca1f5b-582f-44d3-84c6-eadd1efbb643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton btn-actualizar</value>
      <webElementGuid>0dc83d3e-fe50-4691-b8d9-af353131b5c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_parametroformato:tabInfo:j_idt315&quot;,f:&quot;form_parametroformato&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>1c27a6a6-594f-46b2-b43f-4a86c2974f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Actualizar</value>
      <webElementGuid>90b83a1d-daeb-4266-bf06-a8c0c13c130c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_parametroformato:tabInfo:j_idt315&quot;)</value>
      <webElementGuid>f007d663-9821-4224-a6ac-c7b6e40c2871</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='form_parametroformato:tabInfo:j_idt315']</value>
      <webElementGuid>e8bd43af-5cbc-4a8c-9b12-faccc35e1184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_parametroformato:tabInfo:tabFormato']/a</value>
      <webElementGuid>344f06e8-9a09-4fab-bb62-ac7fcc5bad97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Actualizar')]</value>
      <webElementGuid>dadb016c-9516-482d-b41a-d7a76f740048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titulo 20'])[1]/following::a[1]</value>
      <webElementGuid>cc8d4aeb-674f-45aa-9b7d-da95bf9c535a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titulo 19'])[1]/following::a[1]</value>
      <webElementGuid>5e04ec00-7148-4c56-8fa9-e9f7eb03a67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrada'])[1]/preceding::a[2]</value>
      <webElementGuid>b7c22258-7e7c-420e-a9ca-e107e646befc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Derogar'])[1]/preceding::a[2]</value>
      <webElementGuid>78f14c86-6a98-4d41-8087-d0607c633549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Actualizar']/parent::*</value>
      <webElementGuid>f2d7f626-9e55-49e3-b5a4-466ff461284a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[50]</value>
      <webElementGuid>3b4d6682-9cc8-49d0-8a89-5ccb5c7a5189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>c90b8b2d-55d3-4ec3-a0bd-1ac282b53348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'form_parametroformato:tabInfo:j_idt315' and @href = '#' and (text() = 'Actualizar' or . = 'Actualizar')]</value>
      <webElementGuid>7f8023f5-247b-4fb5-8fcd-88e3ebdb60c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
