<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bsqueda_form_parametroformatoconceptofiltro</name>
   <tag></tag>
   <elementGuidId>e86ad52c-f80c-42f4-9b36-37b81c09c6fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>213551e7-fe75-4e98-b4ac-02e79e9ec8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_parametroformato:conceptofiltro</value>
      <webElementGuid>5f195fd4-7d68-4cee-8bc7-2a7e09412108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_parametroformato:conceptofiltro</value>
      <webElementGuid>429a7617-9ef8-46e2-8bd6-abd323b35b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76c407db-b8f9-40eb-ae36-cd05a33da641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ace_valor_campo_estandar ui-state-focus</value>
      <webElementGuid>297f5450-132e-4d95-9c72-560c15a08d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>85419323-e79a-49d8-aefe-5ee569b0bf29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_parametroformato:conceptofiltro&quot;,e:&quot;valueChange&quot;,f:&quot;form_parametroformato&quot;,p:&quot;form_parametroformato:conceptofiltro&quot;});</value>
      <webElementGuid>eeb52fca-bf2a-4b11-9180-6dbdf9121939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>a63c627a-05e9-48ac-8a2c-0af72aba7b10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ca59c7eb-bfa3-4f09-b39e-d2b889d0858a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>421dddd7-54e8-407a-a514-bd6fd92889a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_parametroformato:conceptofiltro&quot;)</value>
      <webElementGuid>e215ead0-3c73-4fa4-b2b7-5eadfe99ce1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_parametroformato:conceptofiltro']</value>
      <webElementGuid>a19e86fc-ec1a-4e86-8896-f1e66e7e69a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='form_parametroformato:parametroFormatoPrincipal']/tbody/tr/td/span/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>4066c41e-141f-4215-b7d3-b26a70b305ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>7ec0e03b-b368-4e86-aa55-2c3dbf53805e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_parametroformato:conceptofiltro' and @name = 'form_parametroformato:conceptofiltro' and @type = 'text']</value>
      <webElementGuid>3964dda0-d5a5-461c-9b46-27ca155c7f6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
