<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Formato_form_parametroformatoformato5</name>
   <tag></tag>
   <elementGuidId>d463ab6c-dbb9-4973-9983-5400ee86badb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7dc07ad2-e3b7-4fc5-8772-499e809814e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_parametroformato:formato</value>
      <webElementGuid>1c25b99d-15c1-45ab-ab6b-e2bec19b20b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>44191ee8-71c1-4d6d-aac4-bd75a40eb0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_parametroformato:formato</value>
      <webElementGuid>e969677f-23e2-48d9-8bb3-18f2642881a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caja_texto</value>
      <webElementGuid>52b30af7-5fd1-48dc-8310-8cfc4a1a94e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3cc66205-a49f-47f8-8805-c9c590daa549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return entero(event);</value>
      <webElementGuid>8ec57e5f-f88a-4a6a-8001-65c4c5dbd033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_parametroformato:formato&quot;)</value>
      <webElementGuid>990c9dda-3caa-40b1-a1b9-429d608b8a06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_parametroformato:formato']</value>
      <webElementGuid>a4cd2605-8594-4c0e-b1cb-3e3873b1957d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='form_parametroformato:parametroFormatoPrincipal']/tbody/tr/td/span/table/tbody/tr/td/div/table/tbody/tr[2]/td/table/tbody/tr/td[2]/input</value>
      <webElementGuid>112d4335-d359-4a40-b370-d6d6c462ef3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>4f85b43c-890a-4bae-8e7c-f61c491657e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_parametroformato:formato' and @type = 'text' and @name = 'form_parametroformato:formato']</value>
      <webElementGuid>bfcc6660-89ff-4a12-9c1c-af53e3549ed4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
