<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Titulo 2_form_parametroformatotabInfoj_idt2751</name>
   <tag></tag>
   <elementGuidId>dddb9e28-35e2-4493-97c6-e06db1d6fba5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;form_parametroformato:tabInfo:j_idt275&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[4]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1225de9-537b-4375-9ce6-270d528f28fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>24a7a015-fa14-46bc-b75c-be6e3bb3a0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_parametroformato:tabInfo:j_idt275</value>
      <webElementGuid>8780289b-e512-4835-8737-84a09934a501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caja_texto</value>
      <webElementGuid>357d2e0a-5428-4153-9288-0ab503e921a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e22965f9-7a6b-44c3-ba8e-62299dc9bed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_parametroformato:tabInfo:j_idt270&quot;)/div[@class=&quot;ui-fieldset-content&quot;]/table[1]/tbody[1]/tr[1]/td[4]/input[@class=&quot;caja_texto&quot;]</value>
      <webElementGuid>1eaaf13a-277e-4e7a-804c-2aad8c044e33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='form_parametroformato:tabInfo:j_idt275']</value>
      <webElementGuid>deccbe55-b2de-4c2e-b299-72992acdb969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form_parametroformato:tabInfo:j_idt270']/div/table/tbody/tr/td[4]/input</value>
      <webElementGuid>478aac02-314a-4416-945c-0ee1066c8382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>9ddc243d-2980-43ad-be04-185e38652067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'form_parametroformato:tabInfo:j_idt275']</value>
      <webElementGuid>fd7a7fcb-4aae-4390-a4fe-d869e3563054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
