<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NoSi1</name>
   <tag></tag>
   <elementGuidId>8dcb3b7b-d58f-46ec-8f32-d5a7341acf43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//fieldset/div/table/tbody/tr[3]/td[2]/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>945e3a5b-8f70-4a8f-a0ee-3cab3df307aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_parametroformato:tabInfo:afectasueldo</value>
      <webElementGuid>e88e3a31-5423-4988-b6f8-e58403bf3d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_parametroformato:tabInfo:afectasueldo</value>
      <webElementGuid>0513058a-723b-448e-a97c-cf11a8e85d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>3516f030-eff0-44e0-aa2a-863effbbd980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>04192799-b336-499c-b3f6-05a9f062c5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	No
	Si
</value>
      <webElementGuid>d86ea01a-2d45-4e98-932e-13d50cfc9279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_parametroformato:tabInfo:afectasueldo&quot;)</value>
      <webElementGuid>e5c84199-724f-450d-8025-98ea80931371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='form_parametroformato:tabInfo:afectasueldo']</value>
      <webElementGuid>cc210c72-3e0c-4a09-ae5f-f8e14810cd43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='form_parametroformato:tabInfo:j_idt199']/div/table/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>fbb7fab3-ce77-4a6f-bf4d-f15f2ce0f534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Afecta Asignación'])[1]/following::select[1]</value>
      <webElementGuid>af4fcabf-edf3-4267-8376-f391f07d90fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Generación Regresión'])[1]/following::select[2]</value>
      <webElementGuid>7a9f00f5-fdf3-4432-a469-c64d75ee21d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Genera Flexible'])[1]/preceding::select[1]</value>
      <webElementGuid>1c48a9cf-920f-41ea-9e7d-5eaf05236711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Control Elaborar'])[1]/preceding::select[2]</value>
      <webElementGuid>1bacb016-ca34-4997-afd1-d7b70a89e15e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/table/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>0fcfc0e6-b831-403e-a650-9c62d97059c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'form_parametroformato:tabInfo:afectasueldo' and @name = 'form_parametroformato:tabInfo:afectasueldo' and (text() = '	No
	Si
' or . = '	No
	Si
')]</value>
      <webElementGuid>bff801aa-6b1e-434d-92fe-6e36089508c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
