<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Base_popupNuevoConceptoHistoricoNominaj_idt2302</name>
   <tag></tag>
   <elementGuidId>32a80787-4331-4342-860e-713f2d88f336</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[2]/td[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;popupNuevoConceptoHistoricoNomina:j_idt2302&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45690c96-b09a-45f8-bcde-023bb180ecd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72610962-aa2c-4ac4-af0e-ee01e4189b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popupNuevoConceptoHistoricoNomina:j_idt2302</value>
      <webElementGuid>c5d13213-00ee-4d39-aa7f-ccfd3cb4dc6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caja_texto</value>
      <webElementGuid>44087e1d-5535-451d-beb1-c1f918ecd79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>126</value>
      <webElementGuid>6a05ffb1-2e77-4d5a-b589-d6b9b0991119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return decimalNegativo(event,this.value);</value>
      <webElementGuid>33bb975a-cdbe-469d-b3a3-cfa8b395209c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupNuevoConceptoHistoricoNomina:j_idt2287_content&quot;)/div[@class=&quot;popupBody&quot;]/table[2]/tbody[1]/tr[2]/td[2]/input[@class=&quot;caja_texto&quot;]</value>
      <webElementGuid>b35c171d-a7f2-4f40-8816-41e0b8d7582d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='popupNuevoConceptoHistoricoNomina:j_idt2302']</value>
      <webElementGuid>5eb08475-d510-4e4f-b1e0-8e28b053cc62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupNuevoConceptoHistoricoNomina:j_idt2287_content']/div[2]/table[2]/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>0a85436d-f552-4d33-b3a9-ea6c03d5a486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>3b1f23ad-778f-4a86-a0ef-cde5c4c9fb9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'popupNuevoConceptoHistoricoNomina:j_idt2302']</value>
      <webElementGuid>40c55494-2bf9-4246-8d7c-3b255d15579c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
