<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Titular_datosPuestoTrabajo_f</name>
   <tag></tag>
   <elementGuidId>1afd614b-78d4-44b7-af7e-f50cffb4582c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/table/tbody/tr/td[2]/table/tbody/tr/td[3]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@class = 'btn_popupInformacion' and @href = '#' and starts-with(@id, 'datosPuestoTrabajo_form') and @onclick = concat('mojarra.jsfcljs(document.getElementById(' , &quot;'&quot; , 'datosPuestoTrabajo_form' , &quot;'&quot; , '),{' , &quot;'&quot; , 'datosPuestoTrabajo_form:_t198' , &quot;'&quot; , ':' , &quot;'&quot; , 'datosPuestoTrabajo_form:_t198' , &quot;'&quot; , ',' , &quot;'&quot; , 'tipoEmpleado' , &quot;'&quot; , ':' , &quot;'&quot; , 'N' , &quot;'&quot; , '},' , &quot;'&quot; , '' , &quot;'&quot; , ');return false')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn_popupInformacion</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>starts with</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datosPuestoTrabajo_form</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.jsfcljs(document.getElementById('datosPuestoTrabajo_form'),{'datosPuestoTrabajo_form:_t198':'datosPuestoTrabajo_form:_t198','tipoEmpleado':'N'},'');return false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datosPuestoTrabajo_form:_t198&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='datosPuestoTrabajo_form:j_idt1191']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='datosPuestoTrabajo_form:datosDeNomina']/table/tbody/tr/td[2]/table/tbody/tr/td[3]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[26]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/table/tbody/tr/td[2]/table/tbody/tr/td[3]/a</value>
   </webElementXpaths>
</WebElementEntity>
