<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mesada_datosPuestoTrabajo_formsueldo</name>
   <tag></tag>
   <elementGuidId>95bf4c01-f640-4e55-9743-d19d10d647af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[10]/td[2]/table/tbody/tr/td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54fbbe55-cc70-4916-be27-52740eed1527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>datosPuestoTrabajo_form:sueldo</value>
      <webElementGuid>eb2c8b75-fa86-4c47-893b-6b592f6bf67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d5f29b0-b012-4e02-92bf-2c25ae2d16f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>datosPuestoTrabajo_form:sueldo</value>
      <webElementGuid>12ccbf68-052f-4a25-bf5b-0d49cbf40989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caja_texto</value>
      <webElementGuid>d70aaeab-a502-44d2-a94e-25585c89725f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>3323241c-f935-48dd-b34f-40c71332834e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return decimal(event,this.value);</value>
      <webElementGuid>e098de1a-f647-448a-808a-de9b8ea2d7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;datosPuestoTrabajo_form:sueldo&quot;)</value>
      <webElementGuid>50f4fb34-9dcc-4017-8d4a-c71e3c3138e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='datosPuestoTrabajo_form:sueldo']</value>
      <webElementGuid>4f4abcc3-3f4e-4025-bf89-ab577df37c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='datosPuestoTrabajo_form:datosDeNomina']/table[2]/tbody/tr[10]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>004839b7-a665-49e8-bbb4-2870637b5ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>d1b0aecb-6273-4436-b591-2b42ca58ae8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'datosPuestoTrabajo_form:sueldo' and @type = 'text' and @name = 'datosPuestoTrabajo_form:sueldo']</value>
      <webElementGuid>7600fab3-3001-4b14-8661-b6a7727b6a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
