<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Cargo_popupCargo_Formj_idt1159</name>
   <tag></tag>
   <elementGuidId>8689a0f8-bada-407d-8131-145fa34e8117</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff00b2c0-172d-438e-ba56-278b166a8953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popupCargo_Form:j_idt1159</value>
      <webElementGuid>7316f04e-76da-49bc-bebb-58bfdaa3cb0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popupCargo_Form:j_idt1159</value>
      <webElementGuid>f980e057-7d62-4c08-8792-26834c76ec0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc9dc85e-f5a6-4898-a685-2e44c48d4b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ace_valor_campo_estandar ui-state-hover ui-state-focus</value>
      <webElementGuid>e9494a0f-9f9f-473d-8033-fdd954f321bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>f8de722a-cd4f-405a-ae2d-4a1f21ea0124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;popupCargo_Form:j_idt1159&quot;,e:&quot;valueChange&quot;,f:&quot;popupCargo_Form&quot;,p:&quot;popupCargo_Form:j_idt1159&quot;,u:&quot;popupCargo_Form&quot;});</value>
      <webElementGuid>f2f13bfe-2d91-4cc8-957c-da6e96ec0fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>1bb0cc02-a151-4a4c-9fba-48f69370a392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5091cb8b-b868-4f68-8cc9-b0fd88fec437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3994c181-4af5-4838-8975-df383f10c3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupCargo_Form:j_idt1159&quot;)</value>
      <webElementGuid>d4bbdb9a-9d32-4cfc-8abf-2bcffe7821d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='popupCargo_Form:j_idt1159']</value>
      <webElementGuid>3a503240-42cb-418b-8f9b-652373054d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupCargo_Form:j_idt1153_content']/div[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>5c42ac1b-3421-4dd4-80f0-671f96ac4ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>ba1cc0c2-b98a-4168-91fc-318c7a3c1922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'popupCargo_Form:j_idt1159' and @name = 'popupCargo_Form:j_idt1159' and @type = 'text']</value>
      <webElementGuid>d0ccaf46-cd98-48a7-aa0e-d4a410b20483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
