<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hora Comienza_jornada_formhoraInicialDI</name>
   <tag></tag>
   <elementGuidId>476689ab-051c-4852-910a-6c65473e0d3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[3]/div/table/tbody/tr[3]/td/table/tbody/tr/td/div/table/tbody/tr/td/table/tbody/tr/td[2]/table/tbody/tr/td/form/div/table[3]/tbody/tr[2]/td[2]/table/tbody/tr[1]/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08a72d2a-1963-45a4-b129-bbfd55404eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jornada_form:horaInicialDI</value>
      <webElementGuid>bec74193-17b0-4e7e-90fe-b6b3c42e8746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1ea54050-eb1e-4d04-8da1-4c066ed8064a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jornada_form:horaInicialDI</value>
      <webElementGuid>290f7cdc-e343-4024-afb0-aa7c0663acb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>69111d8c-2954-4ea2-958a-3f34fc05fecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>60d8c62c-ccc7-4112-8de5-10314a442576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return entero(event);</value>
      <webElementGuid>c0ae2da5-fc53-4cec-88a0-648ce1b2ba9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>mojarra.ab(this,event,'blur',0,'jornada_form:paneltotalhoras jornada_form:panelhorario')</value>
      <webElementGuid>7d25391f-97e6-4a1e-8b62-7a56c2ee36c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jornada_form:horaInicialDI&quot;)</value>
      <webElementGuid>55538975-414d-44ac-a811-67c884ae4d80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jornada_form:horaInicialDI']</value>
      <webElementGuid>0f16a968-c2ea-4b9c-9583-06ee9912b31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jornada_form:idPanelJornada']/table/tbody/tr[6]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>cfe3599a-aa44-4c1e-b3bd-994a77bbb7be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>d6329b8e-14b3-442a-981c-36ebdde94669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jornada_form:horaInicialDI' and @type = 'text' and @name = 'jornada_form:horaInicialDI']</value>
      <webElementGuid>76476b09-f3bc-432b-b7d8-385240a4d0d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
