<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Hora Termina_jornada_formhoraFinalCI</name>
   <tag></tag>
   <elementGuidId>8ae25c64-b3e4-4f2a-97ad-28f59bba7f67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;jornada_form:horaFinalCI&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b72db16-edbf-4027-8ed6-0754698c15e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jornada_form:horaFinalCI</value>
      <webElementGuid>c5da736f-b196-4d88-bfa8-4b516d0c574c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5c00edc-b982-40e8-8dc8-1eca7a413562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jornada_form:horaFinalCI</value>
      <webElementGuid>a57aec46-b7ca-4703-958b-22db6554454b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>8a5373ef-ed28-404a-bab3-94b57e48f3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a4de90e0-302c-4377-8918-5c58c16905e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return entero(event);</value>
      <webElementGuid>28ce3366-87a9-45d3-912d-4f9311b2c942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>mojarra.ab(this,event,'blur',0,'jornada_form:paneltotalcircular jornada_form:panelhorario')</value>
      <webElementGuid>801b593c-656d-4614-82d1-37422819b4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jornada_form:horaFinalCI&quot;)</value>
      <webElementGuid>f3eaa1cd-3db8-4ce8-9924-ecc72edb085c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jornada_form:horaFinalCI']</value>
      <webElementGuid>14862a2a-7e50-4c35-ba43-2581020e1658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jornada_form:idPanelJornada']/table/tbody/tr[8]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>cdfaa619-f980-4c5d-b84f-6463b19665db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>5276460d-acf9-4c3a-87e4-652f93ff4660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'jornada_form:horaFinalCI' and @type = 'text' and @name = 'jornada_form:horaFinalCI']</value>
      <webElementGuid>44de1250-45f5-4891-9a02-be591bb19a39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
