<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SeleccionarDiaria</name>
   <tag></tag>
   <elementGuidId>d51decbd-8c5d-4437-b5b0-b9fd346b6ea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[4]/div/table/tbody/tr[3]/td/table/tbody/tr/td/div/table/tbody/tr/td/table/tbody/tr/td[2]/table/tbody/tr/td/form/div/table[3]/tbody/tr[1]/td[2]/table/tbody/tr/td[4]/select</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d52790e3-796d-4eab-a74f-aa39a586ed10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jornada_form:tipo</value>
      <webElementGuid>4f5818c7-a972-43ea-b510-f85a0d8786be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jornada_form:tipo</value>
      <webElementGuid>29c0fcf2-22cd-4d29-a0e7-d1f364834eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>46e802a8-ac1f-463b-b363-6b5d753b8c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6715eae7-c736-4c9d-913d-00deecbad757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;valueChange&quot;,f:&quot;jornada_form&quot;,p:&quot;jornada_form:tipo&quot;,u:&quot;jornada_form:idPanelJornada&quot;});</value>
      <webElementGuid>14bb361e-9814-475f-8921-d00d642768f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	Seleccionar
	Diaria
</value>
      <webElementGuid>6778f371-d1d8-4daa-81f3-7fb96a740ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jornada_form:tipo&quot;)</value>
      <webElementGuid>a87c5d47-c59b-4528-b0e7-4bbee1f3ded7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='jornada_form:tipo']</value>
      <webElementGuid>5835e284-c4bb-45ff-a82b-d47289bdd144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='jornada_form:idPanelJornada']/table/tbody/tr[4]/td[2]/select</value>
      <webElementGuid>febb98e6-430c-4e00-9387-29397c8b368b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo'])[1]/following::select[1]</value>
      <webElementGuid>aca60bdf-b4f3-402f-b461-62e327202763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acción'])[1]/following::select[2]</value>
      <webElementGuid>6af55097-c2aa-4276-95d4-427a095802e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Día'])[1]/preceding::select[1]</value>
      <webElementGuid>77380d51-6a48-4303-bdff-b6eb0894c701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ui-button'])[1]/preceding::select[1]</value>
      <webElementGuid>8706cc6a-6d7c-4ac0-83a1-1dacef90708f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/select</value>
      <webElementGuid>70690660-44e9-4ff3-b176-2227ad49cb57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'jornada_form:tipo' and @name = 'jornada_form:tipo' and (text() = '	Seleccionar
	Diaria
' or . = '	Seleccionar
	Diaria
')]</value>
      <webElementGuid>f780761e-4fec-446a-947c-20fa7a60da52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
