<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_No se encontr registros_btn-miniadicionar2</name>
   <tag></tag>
   <elementGuidId>8b8eb88a-5789-4985-bf1b-243c200b3925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[6]/table/tbody/tr/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tbody > tr > td > a.btn-miniadicionar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.jsfcljs(document.getElementById('form_FuenteGeneral'),{'form_FuenteGeneral:tab:tablaNotificacion:j_idt214':'form_FuenteGeneral:tab:tablaNotificacion:j_idt214'},'');return false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-miniadicionar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_FuenteGeneral:tab:tablaNotificacion_foot&quot;)/tr[1]/td[@class=&quot;ui-state-default&quot;]/table[1]/tbody[1]/tr[1]/td[1]/a[@class=&quot;btn-miniadicionar&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;mojarra.jsfcljs(document.getElementById('form_FuenteGeneral'),{'form_FuenteGeneral:tab:tablaNotificacion:j_idt214':'form_FuenteGeneral:tab:tablaNotificacion:j_idt214'},'');return false&quot;]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tfoot[@id='form_FuenteGeneral:tab:tablaNotificacion_foot']/tr/td[6]/table/tbody/tr/td/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[40]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/table/tbody/tr/td/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
   </webElementXpaths>
</WebElementEntity>
