<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nmina Eletrnica popup</name>
   <tag></tag>
   <elementGuidId>ae53e8ff-3dde-4b8e-85d6-eb94110458d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[4]/div/table/tbody/tr[3]/td/table/tbody/tr/td/div/form[1]/table/tbody/tr[3]/td/table/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr[2]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[9]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;popup_nominaelectronicaajsute:j_idt868&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2118ca8-cbe6-40e1-89e2-46bdfa043bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82e4e567-c558-4808-9b5f-f614ed542817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popup_nominaelectronicaajsute:j_idt868</value>
      <webElementGuid>3cfcc6ee-59d7-437c-8e3a-8e4f51855b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caja_texto</value>
      <webElementGuid>5b8f60f5-0963-4cd7-9a8e-d751bf7f21a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popup_nominaelectronicaajsute:j_idt863_content&quot;)/div[@class=&quot;popupBody&quot;]/table[1]/tbody[1]/tr[1]/td[1]/input[@class=&quot;caja_texto&quot;]</value>
      <webElementGuid>5a99117f-6ddf-4a0c-a51b-f36cb75393d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='popup_nominaelectronicaajsute:j_idt868']</value>
      <webElementGuid>ff715c55-e5ae-48c4-ac6e-51c031efdc88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup_nominaelectronicaajsute:j_idt863_content']/div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>3036987f-8589-4631-afb9-181e319c834a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>ff81508d-177e-4514-a153-597de202afde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'popup_nominaelectronicaajsute:j_idt868']</value>
      <webElementGuid>ce3675f8-4b23-411d-9ccb-df866cf04306</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
