<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_administrador_usuarioformatabtabla_roles_individualj_idt1611</name>
   <tag></tag>
   <elementGuidId>eb16f700-6172-4f9f-8b64-4d5af0b8258d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[4]/div/table/tbody/tr[3]/td/table/tbody/tr/td/div/form/table/tbody/tr/td/span/div/div/div[4]/div/div/table/tfoot/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b0810d67-0ee3-4c4d-ae37-f37cde27bd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usuarioforma:tab:tabla_roles_individual:j_idt161</value>
      <webElementGuid>3974ce37-546c-4a5c-886d-ebeb8d589254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a076d810-bf18-4b70-91d8-108d4b369cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget btn-miniadicionar</value>
      <webElementGuid>ba131e3a-cbf5-4c19-b02e-b523acc96330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;usuarioforma:tab:tabla_roles_individual:j_idt161&quot;,f:&quot;usuarioforma&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>0d1aec4c-1333-4c50-b6f3-1d4a7eeac025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usuarioforma:tab:tabla_roles_individual:j_idt161&quot;)</value>
      <webElementGuid>b82eaf4b-7020-490f-a19c-ee7cd4d02074</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='usuarioforma:tab:tabla_roles_individual:j_idt161']</value>
      <webElementGuid>ea94cd9c-431c-4ab2-b9dd-397abd6083a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tfoot[@id='usuarioforma:tab:tabla_roles_individual_foot']/tr/td[2]/a</value>
      <webElementGuid>45fbf1cf-cd72-4650-9ea3-3efd5ee469f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[58]</value>
      <webElementGuid>efd1040f-0f03-41b5-b4c4-ebe37ba84204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tfoot/tr/td[2]/a</value>
      <webElementGuid>a6b60bdf-2a68-4aff-aed0-72bf799346e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'usuarioforma:tab:tabla_roles_individual:j_idt161' and @href = '#']</value>
      <webElementGuid>3f0a36bb-66a4-4197-9fc5-0e1610fd1549</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
