<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Administrador_glyphicons glyphicons-exit</name>
   <tag></tag>
   <elementGuidId>61885655-951a-4bb4-9af1-ead8c84c40cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.glyphicons.glyphicons-exit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0d90e3f5-b1a3-4cd5-92c8-41ccc591c205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>62409089-c542-4a92-9a50-53813de10ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Salir</value>
      <webElementGuid>c3debb21-72d9-440a-b984-c475770dffb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.jsfcljs(document.getElementById('j_idt44'),{'j_idt44:j_idt51':'j_idt44:j_idt51'},'');return false</value>
      <webElementGuid>ada0b389-89d8-45a1-9371-155a4db2e8e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-exit</value>
      <webElementGuid>d2140f6d-8742-4a1f-a22e-ed04426b47b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opcionSalir&quot;)/table[@class=&quot;us-icono-menu&quot;]/tbody[1]/tr[1]/td[3]/a[@class=&quot;glyphicons glyphicons-exit&quot;]</value>
      <webElementGuid>a7cc3bb7-d09d-4047-9e71-5adcbff32eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f553cb0-6560-423b-a21d-195c93f300cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>19ccd59b-481f-49be-a459-c63b4f04ca78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Salir</value>
      <webElementGuid>82f232b8-114c-4383-84c2-7fcf59eccbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>mojarra.jsfcljs(document.getElementById('j_idt44'),{'j_idt44:j_idt51':'j_idt44:j_idt51'},'');return false</value>
      <webElementGuid>aa3fada1-4466-41b6-8ab6-a79d55f96b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicons glyphicons-exit</value>
      <webElementGuid>062bfcce-b7c5-4e26-8526-b61e6e84a618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opcionSalir&quot;)/table[@class=&quot;us-icono-menu&quot;]/tbody[1]/tr[1]/td[3]/a[@class=&quot;glyphicons glyphicons-exit&quot;]</value>
      <webElementGuid>f909f7c1-5eef-4606-bd6d-ed1e187054b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;mojarra.jsfcljs(document.getElementById('j_idt44'),{'j_idt44:j_idt51':'j_idt44:j_idt51'},'');return false&quot;]</value>
      <webElementGuid>42bbcba5-ae79-45ef-b6a5-c212f4c5c7c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opcionSalir']/table/tbody/tr/td[3]/a</value>
      <webElementGuid>70abc4fa-3740-4cae-9ca3-b5a90b4ac91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>e1ff441e-0a81-4824-ae24-ab33020f42ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a</value>
      <webElementGuid>0548f45c-d833-493b-b189-6b6103d8e823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Salir']</value>
      <webElementGuid>962a2bd3-0ff4-496b-aa8f-a0913b8a7b69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
