<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_A1            - ADMINISTRACION_organigramalistaPuestosActivosj_idt150</name>
   <tag></tag>
   <elementGuidId>641869f9-db34-4ebd-aed9-a10db0e8b152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[4]/div/table/tbody/tr[3]/td/table/tbody/tr/td/div/form[1]/div/div/div[2]/div[4]/div[2]/div[1]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b257b6d-ae40-4550-8120-ab25f58b85c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organigrama:listaPuestosActivos:j_idt150</value>
      <webElementGuid>bda10539-896b-43d9-a75b-ac0e9faffbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organigrama:listaPuestosActivos:j_idt150</value>
      <webElementGuid>bcffd433-af91-453e-b795-1c91df987681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a8bf935-a9f8-4d27-8016-a606d1672500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all valor_campo_estandar ui-state-focus</value>
      <webElementGuid>23203da0-7b6a-4c8e-8789-42998b67616b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Buscar</value>
      <webElementGuid>6586f4b2-e0fb-43cf-895b-c1b38e4a82ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;organigrama:listaPuestosActivos:j_idt150&quot;,e:&quot;valueChange&quot;,f:&quot;organigrama&quot;,p:&quot;organigrama:listaPuestosActivos:j_idt150&quot;,u:&quot;organigrama:listaPuestosActivos&quot;});</value>
      <webElementGuid>72630925-d09f-4602-ae3b-cf3f2d35eaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e75596a3-aa89-4126-8c46-decf87257867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3e4e1771-6e52-4a13-ae14-6386d5d685fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a1b2f773-0124-418b-8482-0f8da84bcdce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organigrama:listaPuestosActivos:j_idt150&quot;)</value>
      <webElementGuid>1f3dda33-3896-4e79-8017-10c25aae39f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='organigrama:listaPuestosActivos:j_idt150']</value>
      <webElementGuid>f84b74bc-fbca-4175-a6ba-dc1badb3578b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='organigrama:listaPuestosActivos']/div/input</value>
      <webElementGuid>d8dec267-cecc-4193-908c-33254b953bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>3d4892d7-1646-46fe-8539-894582df9810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'organigrama:listaPuestosActivos:j_idt150' and @name = 'organigrama:listaPuestosActivos:j_idt150' and @type = 'text' and @placeholder = 'Buscar']</value>
      <webElementGuid>32958d95-5855-4216-9b48-6437196c871b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
