<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Aplicar</name>
   <tag></tag>
   <elementGuidId>a0ae2e7b-4a36-4f4e-a096-b3bd96fbb527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[4]/div/table/tbody/tr[3]/td/table/tbody/tr/td/div/form[1]/table/tbody/tr/td[2]/span/table[2]/tbody/tr/td[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>80120ae2-5b1d-4d41-a3bd-2c608c91d178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_idt61:j_idt202</value>
      <webElementGuid>89c73eef-aac3-44f5-9775-6c739206276e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>490466dd-ac84-4fe8-b309-81d3814ad12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton btn-aplicar</value>
      <webElementGuid>a54da8f6-d204-48a2-a0f3-221eca0ba809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pfconfirmcommand</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;j_idt61:j_idt202&quot;,f:&quot;j_idt61&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>ef78bed1-2eb3-4ba2-a4d4-15c751b080c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.confirm({source:&quot;j_idt61:j_idt202&quot;,type:&quot;dialog&quot;,escape:true,header:&quot;Aplicar&quot;,message:&quot;DESEA CONFIRMAR&quot;,icon:&quot;pi pi-exclamation-triangle&quot;,beforeShow:&quot;&quot;});return false;</value>
      <webElementGuid>0e0badbc-b93f-476c-b246-8f2a76f9fba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aplicar</value>
      <webElementGuid>73a9b2ef-0c11-460f-a6ca-8f9dee301ae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_idt61:j_idt202&quot;)</value>
      <webElementGuid>db8ca469-17cd-463a-84fd-b22a7d12a30a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='j_idt61:j_idt202']</value>
      <webElementGuid>af938b2d-dc32-4761-a82c-402c0090c567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='j_idt61:generacion']/table[2]/tbody/tr/td/a</value>
      <webElementGuid>1777bb42-628d-439c-b818-9c3abe218721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Aplicar')])[2]</value>
      <webElementGuid>5203334a-9484-47b8-9312-40a80583bad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='de'])[1]/following::a[3]</value>
      <webElementGuid>d248069e-054b-453b-8167-1f3e8a3dca1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO RELACIONADO'])[31]/following::a[3]</value>
      <webElementGuid>4bee092e-2fe9-44f6-a454-454c5c343521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[2]</value>
      <webElementGuid>94c8aa8e-1f88-4e89-876e-40a483821cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::a[2]</value>
      <webElementGuid>a2fe309b-2f9e-4561-bead-077a3c6fb849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aplicar']/parent::*</value>
      <webElementGuid>1487875d-1d4c-4c57-9e89-e87a41f2a9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[32]</value>
      <webElementGuid>d4d73e26-2ad1-4ffe-9f7d-752a380a0949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/table[2]/tbody/tr/td/a</value>
      <webElementGuid>61adcd5a-4498-4eb8-98f0-8d096315185b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'j_idt61:j_idt202' and @href = '#' and (text() = 'Aplicar' or . = 'Aplicar')]</value>
      <webElementGuid>b77a0c24-5041-433c-bf6a-7a9c74b02f1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
