<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Filtrar</name>
   <tag></tag>
   <elementGuidId>9357fa55-d696-444e-88ad-55b8e7e1695e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Filtrar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f965f01-63eb-4973-b840-ef36bff436ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_idt61:j_idt152</value>
      <webElementGuid>55ce384e-9405-4ddd-8595-2d5a08ccf380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>843ef3af-9924-44ef-b3f0-b8b07d0603a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton btn-buscadetalle</value>
      <webElementGuid>87ad1a98-e794-40e2-8d7c-fd5e5801e383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;j_idt61:j_idt152&quot;,f:&quot;j_idt61&quot;,u:&quot;j_idt61&quot;});return false;</value>
      <webElementGuid>de53bb58-7980-4df7-9b96-c71a911a87c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filtrar</value>
      <webElementGuid>53b48da7-f50b-4671-80a6-7bd6b24953e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_idt61:j_idt152&quot;)</value>
      <webElementGuid>50037121-8c26-4e1c-8668-cbe9fb2ed199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='j_idt61:j_idt152']</value>
      <webElementGuid>576576a1-79bd-4917-97d7-4b023b39ab33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j_idt61:panel_content']/table[2]/tbody/tr/td[3]/a</value>
      <webElementGuid>18da6aee-14d6-4895-b3b3-f17904e2715d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Filtrar')]</value>
      <webElementGuid>6165c34a-7a5c-429c-acd8-87bdecd0e1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad Por Pagina'])[1]/following::a[3]</value>
      <webElementGuid>e97f9259-d02e-4421-95fe-c3bf49e07c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rango Fechas'])[1]/following::a[3]</value>
      <webElementGuid>3e6ac6fa-99b4-4e06-8790-a76bf633a0bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identificación'])[2]/preceding::a[1]</value>
      <webElementGuid>5c2eb098-5d14-498d-aa17-c026a67290af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contrato'])[2]/preceding::a[1]</value>
      <webElementGuid>32f46909-1fbe-44e5-b91a-b8cd8b924162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filtrar']/parent::*</value>
      <webElementGuid>fa0c1c9a-e6e9-4406-9db0-e83c06785c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[28]</value>
      <webElementGuid>10d086ac-58e5-4fd3-ab7e-c1c773cf40ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[3]/a</value>
      <webElementGuid>7713c4b7-c2c8-4d0c-808a-14cddedef3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'j_idt61:j_idt152' and @href = '#' and (text() = 'Filtrar' or . = 'Filtrar')]</value>
      <webElementGuid>25d90b9b-1bbc-477c-a99c-0717a2881eb0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
