<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reliquidacion</name>
   <tag></tag>
   <elementGuidId>fbe87b07-60ed-4884-b367-2dd790b2ee50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Reliquidacion')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c552871f-b79c-470e-a462-6d679e4e9f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_mantenimientoregresion:j_idt115</value>
      <webElementGuid>79d920fc-9938-4b0d-80e6-5c3a97934cb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a4ae54da-2af4-4edd-a927-30406cb76639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton btn-ejecutar</value>
      <webElementGuid>73782a88-2f78-45da-be42-46a0ae5f94b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pfconfirmcommand</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_mantenimientoregresion:j_idt115&quot;,f:&quot;form_mantenimientoregresion&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>a6d03d06-7a75-4b7a-bcc2-dcd35711eba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.confirm({source:&quot;form_mantenimientoregresion:j_idt115&quot;,type:&quot;dialog&quot;,escape:true,header:&quot;Reliquidacion&quot;,message:&quot;DESEA CONFIRMAR&quot;,icon:&quot;pi pi-exclamation-triangle&quot;,beforeShow:&quot;&quot;});return false;</value>
      <webElementGuid>00e6e3e9-9cab-41d1-9909-88707b5c711d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reliquidacion</value>
      <webElementGuid>62938dc0-b34c-459a-84e7-b5a9058e8227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_mantenimientoregresion:j_idt115&quot;)</value>
      <webElementGuid>c70818b2-dac2-4acf-9705-9b1ad9c4f4a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='form_mantenimientoregresion:j_idt115']</value>
      <webElementGuid>838e4ee2-488d-4204-8b86-6ffa562782dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='form_mantenimientoregresion:panel_registros']/tbody/tr[2]/td/table/tbody/tr/td/a</value>
      <webElementGuid>3d0c1039-ce74-4066-8d65-14b70ae8c66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reliquidacion')]</value>
      <webElementGuid>a137be27-fefc-4568-b467-a4561b9dfe35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periodo en Proceso'])[2]/following::a[1]</value>
      <webElementGuid>3f00d1aa-45a7-4f5f-9a57-39fa56348a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PM202106'])[1]/following::a[1]</value>
      <webElementGuid>cf1cb352-790a-4172-be25-74866150b342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::a[3]</value>
      <webElementGuid>aa0c35e3-ddf4-4308-b5e3-75f410d14cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Si'])[1]/preceding::a[3]</value>
      <webElementGuid>3b4a25f9-4bca-443d-a78d-75b84a916d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reliquidacion']/parent::*</value>
      <webElementGuid>f41e9707-c8b4-47ac-8ae9-54441751bfc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[25]</value>
      <webElementGuid>c6e2253f-3cc7-4c80-b7ea-7dd165207f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/a</value>
      <webElementGuid>6a041d30-9f66-418e-bcb7-5cd3459ae295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'form_mantenimientoregresion:j_idt115' and @href = '#' and (text() = 'Reliquidacion' or . = 'Reliquidacion')]</value>
      <webElementGuid>423e3b1e-cc76-46fa-8533-a825c9027d3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
