<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Regresion aplicada satifactoriamente</name>
   <tag></tag>
   <elementGuidId>786d3817-8ba2-4746-ad8e-ee1bafebdb7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.us-margin-popup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/table/tbody/tr/td/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8e4c311f-f4dd-45a8-8669-754124474598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>us-margin-popup</value>
      <webElementGuid>065dc94c-f472-465d-9f03-fccbc6425f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Regresion aplicada satifactoriamente.</value>
      <webElementGuid>bf94937d-5c8c-469a-a0ca-196f86dcf946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmInfo_popupEspera:contenedorEspera&quot;)/tbody[1]/tr[1]/td[1]/div[@class=&quot;us-margin-popup&quot;]</value>
      <webElementGuid>ccc36add-016b-4deb-ac8b-c91fa5b13958</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='frmInfo_popupEspera:contenedorEspera']/tbody/tr/td/div</value>
      <webElementGuid>a95a5b4c-e6eb-4c9b-8e76-816d7f8e8fe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='de'])[1]/following::div[5]</value>
      <webElementGuid>e706fdf5-34aa-441c-a723-46c8b9ea65c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO RELACIONADO'])[31]/following::div[6]</value>
      <webElementGuid>308dd960-96ea-4964-8a2f-ece6c9ed12d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[8]</value>
      <webElementGuid>45559dc2-8a83-4152-b422-db904c6dab69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[8]</value>
      <webElementGuid>d1169c1d-12cb-4d0a-8d14-1ebdad49987f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Regresion aplicada satifactoriamente.']/parent::*</value>
      <webElementGuid>2cb8a364-e8eb-4d81-a07a-a3ba81909321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/div</value>
      <webElementGuid>3a1c567d-00a5-443f-a250-4079f82e532e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Regresion aplicada satifactoriamente.' or . = 'Regresion aplicada satifactoriamente.')]</value>
      <webElementGuid>6bc3997d-c3f6-40f9-8936-25de61adbc91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
