<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filtro Empleado_form_popupEmpleadoj_idt1928</name>
   <tag></tag>
   <elementGuidId>dee61654-9191-4971-b4a5-35c92f07cab7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/table/tbody/tr/td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2637817d-2aad-459f-b06c-bf0bdce82817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_popupEmpleado:j_idt1928</value>
      <webElementGuid>65b8f7e5-ac94-4046-b76e-c778c987b820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b5ede2d-5a61-420c-9d9d-85d9a8b25215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_popupEmpleado:j_idt1928</value>
      <webElementGuid>e4edad2e-e75f-4269-9ce1-9223d534a524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1851</value>
      <webElementGuid>35014a47-0c17-4bec-b4c2-2214627e3ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ace_valor_campo_estandar</value>
      <webElementGuid>cd57ccff-5c48-423a-8ac9-e7868480e83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>3520a38d-7dd2-4289-854b-058f6dd1d4aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Debe definir un filtro con 4 o mas caracteres</value>
      <webElementGuid>4052a319-c7e2-474e-9e69-2e22c39ac665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;valueChange&quot;,f:&quot;form_popupEmpleado&quot;,p:&quot;form_popupEmpleado:j_idt1928&quot;,u:&quot;form_popupEmpleado&quot;});</value>
      <webElementGuid>8190ac5b-0aff-4b1b-a503-da602315733b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_popupEmpleado:j_idt1928&quot;)</value>
      <webElementGuid>6eb570b7-1345-4dc5-ad9d-d8090ca45870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_popupEmpleado:j_idt1928']</value>
      <webElementGuid>2d087d1e-c3e5-4bc6-811c-9a615875c84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_popupEmpleado:idPopupEmpleado_content']/div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>6115f7a8-ce2c-4955-ba9e-c4d5445094f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>8ef212f2-cba6-4ff8-b93e-3e443c88a7f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_popupEmpleado:j_idt1928' and @type = 'text' and @name = 'form_popupEmpleado:j_idt1928' and @title = 'Debe definir un filtro con 4 o mas caracteres']</value>
      <webElementGuid>03126d58-7019-43fd-abd1-1b162aedea3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
