<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ico3</name>
   <tag></tag>
   <elementGuidId>70da0b12-418a-4b81-a777-33f6b4c4b450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='form_ActosAdministrativos:tabla_principal_1:2:j_idt80']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d72e6cd-9fe6-4b75-a8dc-732139ced70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_ActosAdministrativos:tabla_principal_1:2:j_idt80</value>
      <webElementGuid>a70972f1-2c31-4755-b1d7-cd953e6af780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>015d7e4e-b8c0-4a15-a0d6-00b833b4b645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget glyphicons glyphicons-check x2 us-gris</value>
      <webElementGuid>538d46ec-6b11-4b6b-804a-788eb5edf642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_ActosAdministrativos:tabla_principal_1:2:j_idt80&quot;,f:&quot;form_ActosAdministrativos&quot;,u:&quot;form_ActosAdministrativos&quot;,pa:[{name:&quot;estados&quot;,value:&quot;Legalizar&quot;}]});return false;</value>
      <webElementGuid>194dff94-b44b-4272-b2db-aa2631fc754e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_ActosAdministrativos:tabla_principal_1:2:j_idt80&quot;)</value>
      <webElementGuid>cd0d0403-874d-4f4d-96bf-768ea6eab3b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='form_ActosAdministrativos:tabla_principal_1:2:j_idt80']</value>
      <webElementGuid>1ab33916-8e3b-4eed-8c6e-62dba6446129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='form_ActosAdministrativos:tabla_principal_1_data']/tr[3]/td/a</value>
      <webElementGuid>0becb811-62cc-4bee-b6ae-4f1a33de04ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[44]</value>
      <webElementGuid>012da13a-16bf-4ce3-b98e-57c2efc0ef42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/a</value>
      <webElementGuid>5065efa3-d026-477a-ae2b-49963ad7e6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'form_ActosAdministrativos:tabla_principal_1:2:j_idt80' and @href = '#']</value>
      <webElementGuid>85312db6-e9ad-4ca5-acbd-26c02df08ad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
