<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filtrar por Identificacin_form_ActosAdministrativostabla_principal_actosj_idt119filter</name>
   <tag></tag>
   <elementGuidId>53c8bec3-5c24-4c17-8e0f-0961b7c64b68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[3]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>373a2f0a-7b4f-44b8-807f-b62c1f31ed74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_ActosAdministrativos:tabla_principal_actos:j_idt119:filter</value>
      <webElementGuid>fb1458bd-f84a-40dc-991c-85ddd10f2f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_ActosAdministrativos:tabla_principal_actos:j_idt119:filter</value>
      <webElementGuid>b601150f-85aa-4a3d-b508-6d568dfc645a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-column-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-focus</value>
      <webElementGuid>78e7bba4-8589-4dca-8373-2570f17e0ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c125cb9b-9697-4589-9990-c601b6f63ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>form_ActosAdministrativos:tabla_principal_actos:j_idt119:filter_label</value>
      <webElementGuid>2615b515-c62c-41b8-bb4c-a26f5961d2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>429e1158-59ca-497c-89d5-6d26e19e93b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0c3af418-757f-4f52-b96f-ed060124e431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d89c0d4-0be1-4504-9121-27ab62c73740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_ActosAdministrativos:tabla_principal_actos:j_idt119:filter&quot;)</value>
      <webElementGuid>fdc7a713-1447-4e86-8ec1-347e3ed48f6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_ActosAdministrativos:tabla_principal_actos:j_idt119:filter']</value>
      <webElementGuid>d9036ef5-a761-4acb-8e20-a611ae161a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='form_ActosAdministrativos:tabla_principal_actos:j_idt119']/input</value>
      <webElementGuid>24e4b6c7-8eb0-4308-a836-46235d81571e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/input</value>
      <webElementGuid>4c35b579-17af-43c4-9213-f41b6bd1fa99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_ActosAdministrativos:tabla_principal_actos:j_idt119:filter' and @name = 'form_ActosAdministrativos:tabla_principal_actos:j_idt119:filter']</value>
      <webElementGuid>fba38b28-cda7-4de2-abcd-abe7828105f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
