<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__hojaVidaseccionj_idt1968idTexto</name>
   <tag></tag>
   <elementGuidId>d31b9dda-dd0a-4074-bd94-5eb6f673201d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[9]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af5c87ba-7de0-48eb-a498-e9daa24f2456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hojaVida:seccion:j_idt196:8:idTexto</value>
      <webElementGuid>82a139bd-3395-4a5c-87e0-303a5a35be0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b00b7d2-8c7d-40d6-af0a-1e5b35755fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>hojaVida:seccion:j_idt196:8:idTexto</value>
      <webElementGuid>9b367b19-f77c-4014-b26d-79e8632684b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar  </value>
      <webElementGuid>be03fa72-8c44-487d-a371-a340c2fa4090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>8bc98ee5-2e08-47db-b7a4-5adb0323efe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>2ca5ecc2-1d4b-4d42-a7c5-f3716dc0342c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>026c0393-a492-45f1-abb8-fd9d94585149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>hojaVida:seccion:j_idt196:8:j_idt207</value>
      <webElementGuid>14703e48-2938-46da-869c-c234d4e98f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hojaVida:seccion:j_idt196:8:idTexto&quot;)</value>
      <webElementGuid>7ba1fbc8-ee59-47d5-a64d-a5a9615f9a7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hojaVida:seccion:j_idt196:8:idTexto']</value>
      <webElementGuid>5d7736fa-9a6b-40ca-ac4a-fb0c0dafb37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hojaVida:seccion:j_idt192']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[9]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>a3a7fd9d-12f2-4f9d-89fa-f7fcf3253953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>3806f1c2-f219-475d-bff2-f4c3de789a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hojaVida:seccion:j_idt196:8:idTexto' and @type = 'text' and @name = 'hojaVida:seccion:j_idt196:8:idTexto']</value>
      <webElementGuid>b80d1e60-8f47-4d07-a560-4120e4f07ede</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
