<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_PRUEBA</name>
   <tag></tag>
   <elementGuidId>8a9516b3-ff64-4daa-ab78-c2f91b1a2d99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[9]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr.ui-widget-content.ui-datatable-even.ui-datatable-selectable.ui-state-highlight.fila_tabla_ace.ui-state-hover > td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f3c2141d-fcc9-4e6f-b9e6-f99266e99fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>0e2dedae-be2f-4db9-96e5-80b211ce8025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PRUEBA</value>
      <webElementGuid>d4f31cfd-2ccf-48ac-b950-a6f6e265648c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupCitacion_form:listaEtapas_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-even ui-datatable-selectable ui-state-highlight fila_tabla_ace ui-state-hover&quot;]/td[1]</value>
      <webElementGuid>573ce0c5-9027-4a44-994e-3d91da3f37f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='popupCitacion_form:listaEtapas_data']/tr[9]/td</value>
      <webElementGuid>f3947860-13d6-442c-89c1-d0afbb8769b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contratación'])[1]/following::td[1]</value>
      <webElementGuid>243b9538-76ce-4078-b12d-5c45bd6616ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrevista Jefe Inmediato'])[1]/following::td[2]</value>
      <webElementGuid>41344445-d86f-4a99-8b78-ff13dad73716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prueba Proceso Selección Etapa Proceso'])[1]/preceding::td[1]</value>
      <webElementGuid>08a28c9a-6969-4074-9499-84667d0a3d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitud Competencia Selección'])[1]/preceding::td[3]</value>
      <webElementGuid>893a451c-9784-44ec-9906-99f6b0ad3244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PRUEBA']/parent::*</value>
      <webElementGuid>b847e37f-7301-44ea-8f8a-60d422c7eb98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td</value>
      <webElementGuid>ea247f4b-d6c7-4094-b949-55464bf2a3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'PRUEBA' or . = 'PRUEBA')]</value>
      <webElementGuid>77ff6186-226e-41e0-9f3a-e386f0736337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
