<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Seleccione --DescuentoNo RecaudoNovedad hacia NminaPrestamo</name>
   <tag></tag>
   <elementGuidId>b423a68f-c8d2-4db7-bdbd-debc64cc849c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]/td[5]/select
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a8599456-24ce-4129-9cbe-ef273efd9526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>formDetalleTipoBeneficioBienestar:formaRecaudo</value>
      <webElementGuid>06b4917d-0899-4957-8c98-46621a0468f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>formDetalleTipoBeneficioBienestar:formaRecaudo</value>
      <webElementGuid>a7c17ba6-eb8b-4afc-ae0b-eb607a427487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>9fa6a195-622d-4e9d-a141-3d6808f954a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>39d4f70b-a11e-4445-826e-3d558419c7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;change&quot;,f:&quot;formDetalleTipoBeneficioBienestar&quot;,p:&quot;formDetalleTipoBeneficioBienestar&quot;,u:&quot;formDetalleTipoBeneficioBienestar&quot;});</value>
      <webElementGuid>fcd0786f-9727-498e-8260-23735b95d3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	-- Seleccione --
	Descuento
	No Recaudo
	Novedad hacia Nómina
	Prestamo
</value>
      <webElementGuid>140356f2-598a-4524-b271-a1d35e86ad3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formDetalleTipoBeneficioBienestar:formaRecaudo&quot;)</value>
      <webElementGuid>14e262de-57f8-49a8-8578-a64e4710b671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='formDetalleTipoBeneficioBienestar:formaRecaudo']</value>
      <webElementGuid>56a9269e-af83-4d26-aef3-3c33ebf248fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formDetalleTipoBeneficioBienestar']/table/tbody/tr/td/table/tbody/tr[6]/td[2]/select</value>
      <webElementGuid>3cbf54f2-626d-4f6d-8b63-0788c6b4d0ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forma Recaudo *'])[1]/following::select[1]</value>
      <webElementGuid>4801d204-8589-4653-b788-5c4147e13265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dirigido a *'])[1]/following::select[2]</value>
      <webElementGuid>eef8745f-f760-4700-a935-eadc2fb6e7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maneja Tarifas *'])[1]/preceding::select[1]</value>
      <webElementGuid>0eb117d0-3943-497c-97d3-c985a92e27a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programación Por Periodo *'])[1]/preceding::select[2]</value>
      <webElementGuid>46e960ef-6f0a-4e14-8ab0-7a4f54da0e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/select</value>
      <webElementGuid>ec1459b8-f2b3-4b61-975b-27c30a43c7b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
