<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_sarawebwebcommonauditoriaauditoria.jsf</name>
   <tag></tag>
   <elementGuidId>9296fdd6-3bea-4dcb-b7f4-f738edf936fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/div/div/table/tbody/tr/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>be38fd9c-7624-4966-9d08-d4eb1cd4378d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>e05ce423-c44b-4268-bf35-0a20cf51e82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>/saraweb/webcommon/auditoria/auditoria.jsf</value>
      <webElementGuid>faf9b0fb-1013-4d20-8614-dc883b415618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_peticion:j_idt337:tabla_peticion_data&quot;)/tr[@class=&quot;ui-widget-content ui-datatable-even fila_tabla_ace&quot;]/td[4]</value>
      <webElementGuid>ea1dda63-2b67-4a6d-a14a-88d318adba89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='form_peticion:j_idt337:tabla_peticion_data']/tr/td[4]</value>
      <webElementGuid>fd0ea558-c643-4b1b-8398-655e01315cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pagina'])[1]/following::td[1]</value>
      <webElementGuid>a4d30751-646b-4d48-a0fa-030ca81865b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha'])[1]/following::td[4]</value>
      <webElementGuid>52cefab9-0590-45d6-812e-1767a85f0e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrador'])[2]/preceding::td[1]</value>
      <webElementGuid>24635afe-c91b-47e4-96a3-8e093c01cc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sarads_jboss (compensacionds)'])[1]/preceding::td[2]</value>
      <webElementGuid>ae4c08e7-2d3f-4924-ac8e-8d075ace44eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='/saraweb/webcommon/auditoria/auditoria.jsf']/parent::*</value>
      <webElementGuid>a05d7afa-fa5f-4c96-9caf-b977206dc78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/table/tbody/tr/td[4]</value>
      <webElementGuid>41778d66-a426-4283-98ba-d37589063974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '/saraweb/webcommon/auditoria/auditoria.jsf' or . = '/saraweb/webcommon/auditoria/auditoria.jsf')]</value>
      <webElementGuid>c8e59652-58dd-4b3d-bd05-ff7327765e58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
