<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Permisos Por Rol</name>
   <tag></tag>
   <elementGuidId>ad549c30-f6ce-497f-bf1a-2f139f29da44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Permisos Por Rol']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>40a64954-67e3-437c-ab32-6ae03999c7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rolAcceso:j_idt63:j_idt65:j_idt76</value>
      <webElementGuid>a359adcf-1488-415a-aec1-dc94014e8d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a8851e5e-79a8-44e5-b536-c814fc2eb4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget</value>
      <webElementGuid>5e60df96-6b45-48b3-97b1-e6074fec4a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;rolAcceso:j_idt63:j_idt65:j_idt76&quot;,f:&quot;rolAcceso&quot;,u:&quot;areaAplicacion&quot;,onco:function(xhr,status,args,data){;}});return false;</value>
      <webElementGuid>e766c69f-7d81-49e4-aff1-b1650c684af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Permisos Por Rol </value>
      <webElementGuid>cea754bb-96ac-4028-9358-6cd50274359b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rolAcceso:j_idt63:j_idt65:j_idt76&quot;)</value>
      <webElementGuid>5f6b86be-bed0-44f9-935c-c9f447a1015c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='rolAcceso:j_idt63:j_idt65:j_idt76']</value>
      <webElementGuid>eef4758e-9a9f-4df3-9428-30a2d56bf041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rolAcceso:j_idt63:j_idt65:j_idt66']/table[2]/tbody/tr/td/a</value>
      <webElementGuid>81c495d7-ae34-4bc9-b882-1633ad526348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Permisos Por Rol')]</value>
      <webElementGuid>319748dc-e8d5-4be0-8adb-52123ebcc717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permisos'])[1]/following::a[2]</value>
      <webElementGuid>103ab98e-9f95-4672-ad2c-edff166a58a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parametros de Formularios'])[1]/following::a[6]</value>
      <webElementGuid>0d4ac3e2-afb3-4acc-aad0-5d3e45479856</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permisos Por Login Usuario'])[2]/preceding::a[1]</value>
      <webElementGuid>ada3bdb9-d411-48cf-94ee-b2d66719a80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Control Acceso'])[1]/preceding::a[2]</value>
      <webElementGuid>f8196cea-ee23-418a-a866-4d1c04dc926a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Permisos Por Rol']/parent::*</value>
      <webElementGuid>c25ae15c-2fad-4475-b198-1d8cd145ec0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[41]</value>
      <webElementGuid>f23ac9aa-705a-4e99-a0e7-0199692b2597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td/a</value>
      <webElementGuid>925da4b6-f4be-4258-b51c-81011089b378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'rolAcceso:j_idt63:j_idt65:j_idt76' and @href = '#' and (text() = 'Permisos Por Rol ' or . = 'Permisos Por Rol ')]</value>
      <webElementGuid>5a96d6f9-81d8-442d-84a8-874d5d287941</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
