<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Borrar Permisos Actuales y Copiar Todo</name>
   <tag></tag>
   <elementGuidId>5601125b-f62a-4e32-a83b-d8a2e8921caf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td > label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>e1753032-ef4b-481c-b57a-a1967d39c3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>form_popupCopiarPermisosRolAcceso:tipo:0</value>
      <webElementGuid>07777af6-e678-4a3c-8474-e4acd4a99187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Borrar Permisos Actuales y Copiar Todo</value>
      <webElementGuid>823889a5-4018-4e66-8da4-a8c40f715508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_popupCopiarPermisosRolAcceso:tipo&quot;)/tbody[1]/tr[1]/td[1]/label[1]</value>
      <webElementGuid>dc42c6b1-c4df-4c95-9c0a-830a12a572d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='form_popupCopiarPermisosRolAcceso:tipo']/tbody/tr/td/label</value>
      <webElementGuid>4ed20d50-d91b-4cbb-a216-17d4127a59bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copiar Permisos'])[2]/following::label[1]</value>
      <webElementGuid>3577f6c7-27aa-4cef-9dc9-82d1c0a5b1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Para asociar o desasociar realice clic sobre el registro'])[1]/following::label[2]</value>
      <webElementGuid>04bf7530-5753-4b29-a5b9-bb11924c74c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copiar Diferencias'])[1]/preceding::label[1]</value>
      <webElementGuid>ab87049b-cc9c-4bd0-9095-96ba4774376e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Control Acceso'])[1]/preceding::label[2]</value>
      <webElementGuid>c918dcb5-a10c-4f6b-a9e0-e7f566feaea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Borrar Permisos Actuales y Copiar Todo']/parent::*</value>
      <webElementGuid>0b0d08ee-d85f-4df9-abc0-3f9ce9cb2623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/label</value>
      <webElementGuid>e76a5cc2-188d-490e-b6c7-6c46c9e4569d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' Borrar Permisos Actuales y Copiar Todo' or . = ' Borrar Permisos Actuales y Copiar Todo')]</value>
      <webElementGuid>d2a5c057-f394-457e-a16a-db402fb35e98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
