<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Concepto</name>
   <tag></tag>
   <elementGuidId>b810f89b-eb44-48f7-a854-46b186b388ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Concepto')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>26175245-0803-406a-9200-814eee585824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calculoNomina:j_idt208:j_idt2487</value>
      <webElementGuid>2ea68a6d-3fff-4daa-a5aa-ffaa82dc5300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3dad2f4f-4765-4d71-a6ef-72b4dd6706e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton us-menuhorizontal</value>
      <webElementGuid>b72dc79b-57f1-4586-a141-c3a7b7af16b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;calculoNomina:j_idt208:j_idt2487&quot;,f:&quot;calculoNomina&quot;,u:&quot;calculoNomina&quot;,onco:function(xhr,status,args,data){;}});return false;</value>
      <webElementGuid>a1053b61-4655-4a54-a1f1-e6fdaa715274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Concepto </value>
      <webElementGuid>18baab40-97d9-40a0-a0b0-e77501eabd2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calculoNomina:j_idt208:j_idt2487&quot;)</value>
      <webElementGuid>b9dc79da-c68c-46bb-a9c2-0153166556cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='calculoNomina:j_idt208:j_idt2487']</value>
      <webElementGuid>bd740733-47a1-4802-bdb7-c62cdfd05448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='calculoNomina']/div[2]/table/tbody/tr/td/div/a[2]</value>
      <webElementGuid>3cc7129a-3bcd-4770-b0f6-be18f737efed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Concepto')]</value>
      <webElementGuid>0c076762-dd68-441e-9c0a-0008c80fed9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Almanza Rosas Silvis'])[1]/following::a[3]</value>
      <webElementGuid>8771e223-9984-4488-b70e-125a91c74f71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concepto'])[2]/preceding::a[5]</value>
      <webElementGuid>f38a7c2c-c56a-4f05-9e7a-7eefffdb6fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concepto'])[3]/preceding::a[5]</value>
      <webElementGuid>d07f7cf9-d9ca-4c45-a717-960a132bad61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Concepto']/parent::*</value>
      <webElementGuid>f161cb92-b089-4152-b0fa-68ffc88ae733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[23]</value>
      <webElementGuid>042cbe1f-c1b2-491a-aae9-aaf91c00401b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>8de68c66-40c3-4ad2-9a66-998806fbc558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'calculoNomina:j_idt208:j_idt2487' and @href = '#' and (text() = 'Concepto ' or . = 'Concepto ')]</value>
      <webElementGuid>a2f7de89-8f99-4d80-98f0-3f4d25e018f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
