<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Liquidar</name>
   <tag></tag>
   <elementGuidId>b46c69fd-eb26-4751-b5e1-26fd2810d170</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Liquidar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2761352e-5cef-4153-885f-b3d3d42fa892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calculoNomina:j_idt281</value>
      <webElementGuid>6233e7f6-2867-4a03-8cba-54a6a0b1bed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9ed101d1-4fbd-43f6-901b-323ea89cf9ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton btn-liquida</value>
      <webElementGuid>94d7b361-44f1-402a-bd24-156551559a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pfconfirmcommand</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;calculoNomina:j_idt281&quot;,f:&quot;calculoNomina&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>50e7f02c-e350-473c-80e1-a4d154912429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.confirm({source:&quot;calculoNomina:j_idt281&quot;,type:&quot;dialog&quot;,escape:true,header:&quot;Liquidar&quot;,message:&quot;DESEA CONFIRMAR&quot;,icon:&quot;pi pi-exclamation-triangle&quot;,beforeShow:&quot;&quot;});return false;</value>
      <webElementGuid>e3628992-25e4-43e2-87c4-6da9c71a07f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Liquidar</value>
      <webElementGuid>2e0ef9b7-e8fa-4fa5-b696-0e984d4b43c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calculoNomina:j_idt281&quot;)</value>
      <webElementGuid>88c10a72-75b6-420e-a15d-a844fb37ddd2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='calculoNomina:j_idt281']</value>
      <webElementGuid>5f02b875-2b16-4e90-8a4d-600ad44ef587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='calculoNomina:j_idt210']/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>e4f0b760-0de4-4433-972e-36dd1b75fc38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Liquidar')]</value>
      <webElementGuid>77b1a89f-2bd7-49cd-9111-e0cbdceae332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Neto Nomina'])[1]/following::a[2]</value>
      <webElementGuid>8f497087-3240-48ea-843d-ba0fcbbd5dce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retencion En La Fuente Salarios'])[1]/following::a[2]</value>
      <webElementGuid>853707d5-d985-4d8d-9b92-9daba4f62935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguimiento'])[1]/preceding::a[1]</value>
      <webElementGuid>8635badb-8aac-4890-9f5f-ba374365884a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comprobante'])[1]/preceding::a[4]</value>
      <webElementGuid>7184c226-e7da-437f-be5e-51f21824fec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Liquidar']/parent::*</value>
      <webElementGuid>98d20211-6e19-468b-8357-8d8393a2add2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[29]</value>
      <webElementGuid>43dac34d-2435-486f-877d-aec3555990a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/table/tbody/tr/td[2]/a</value>
      <webElementGuid>9750c23b-7282-49d8-84b8-3437e97e79db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'calculoNomina:j_idt281' and @href = '#' and (text() = 'Liquidar' or . = 'Liquidar')]</value>
      <webElementGuid>c59d2c25-bb80-4535-b393-e183cdd2e52d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
