<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_chkbox-box17</name>
   <tag></tag>
   <elementGuidId>285246a3-5ddc-4bea-8255-9af459b19da0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[17]/td/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ui-chkbox-box.ui-widget.ui-corner-all.ui-state-default.ui-state-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ca42ea78-18ae-4710-a5f5-ae68e192f355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-chkbox-box ui-widget ui-corner-all ui-state-default ui-state-hover</value>
      <webElementGuid>6d17c692-b72a-44a0-977a-0dea05edb2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inscripcionEventosPopupForm:j_idt1241:16:j_idt1258&quot;)/div[@class=&quot;ui-chkbox-box ui-widget ui-corner-all ui-state-default ui-state-hover&quot;]</value>
      <webElementGuid>8da1811d-2150-4033-bcb6-87043936db7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inscripcionEventosPopupForm:j_idt1241:16:j_idt1258']/div[2]</value>
      <webElementGuid>320c5328-55d4-449e-b2c5-0534670d004c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Crew'])[10]/following::div[3]</value>
      <webElementGuid>872bf005-0979-4cc4-912b-39ed86cae4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subdireccion General'])[12]/following::div[3]</value>
      <webElementGuid>a5ca4fbe-287c-4841-807b-fc94d21cf624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aya Silva Cindy Ximena'])[1]/preceding::div[1]</value>
      <webElementGuid>f8c2f3cc-b666-4893-81ed-a7857e98f087</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interna'])[2]/preceding::div[1]</value>
      <webElementGuid>fd7eead5-854a-41ce-9020-11e10bb73cd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td/div/div[2]</value>
      <webElementGuid>1a7de267-da01-4021-bbaa-e4d612b112b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
