<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Entidad Viatico_popupSeleccionEntidadViaticoFormfiltro</name>
   <tag></tag>
   <elementGuidId>67b1b874-108f-4165-bf92-bc88301a608f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec4d83ef-02b3-41ab-921a-4e1a38516a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popupSeleccionEntidadViaticoForm:filtro</value>
      <webElementGuid>ec8d0f88-6109-4f2e-b912-94dd4c839308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7df848e9-4ebc-412e-b3a8-dc091427db39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popupSeleccionEntidadViaticoForm:filtro</value>
      <webElementGuid>b1ffd447-7f65-48cd-98e8-7443b5021b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>e2788ed5-6f67-441b-8382-2b0b7f7d54b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>f6c944ef-7678-49b7-9089-c80a526a45ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupSeleccionEntidadViaticoForm:filtro&quot;)</value>
      <webElementGuid>fd717f34-2629-4b70-8a61-a656bbf4acea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='popupSeleccionEntidadViaticoForm:filtro']</value>
      <webElementGuid>bdcf917d-cf2c-4c8c-bdb9-8dc3d9dae368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupSeleccionEntidadViaticoForm:j_idt1893_content']/div[2]/input</value>
      <webElementGuid>31ec0c69-e032-46ee-b1f0-30746e83a5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>53278ef5-0e70-4301-99f0-008b6d44c638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'popupSeleccionEntidadViaticoForm:filtro' and @type = 'text' and @name = 'popupSeleccionEntidadViaticoForm:filtro']</value>
      <webElementGuid>b73c54e9-2952-48de-bbdf-f9dc95480af8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
