<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Concepto</name>
   <tag></tag>
   <elementGuidId>18849449-f342-404e-8a45-e4fa37ca144e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div[3]/div/table/tbody/tr[3]/td/table/tbody/tr/td/div/form[1]/fieldset/div/div[2]/table[1]/tbody/tr/td/div/a[1]
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//em[starts-with(@id, 'calculoNomina:') and (text() = 'Concepto' or . = 'Concepto')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>4f488b7b-ac23-44c8-a1a5-6a9a64ec88ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>starts with</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calculoNomina:</value>
      <webElementGuid>c98ff349-3e35-425e-8829-fb83479cc637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if(ice.ace.util.isEventSourceInputElement(event)) event.cancelBubble = true;</value>
      <webElementGuid>c1dbd702-fc82-481e-9d8b-5a6e47fb26a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Concepto</value>
      <webElementGuid>02c03eb8-b6a2-4e4a-9227-f7c22916df44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calculoNomina:j_idt151Lbl&quot;)</value>
      <webElementGuid>b3feda5c-b02a-4a30-bb8f-3801ef26dc4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//em[@id='calculoNomina:j_idt151Lbl']</value>
      <webElementGuid>8650f838-2925-472e-b0c1-111cc792deb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calculoNomina:j_idt151tab1']/em</value>
      <webElementGuid>e07a8ac1-6a45-46c4-b624-e6aece6591ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adicionales'])[1]/following::em[1]</value>
      <webElementGuid>d62a590e-4cf7-4050-836e-90fbc10da2bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguimiento'])[1]/following::em[2]</value>
      <webElementGuid>b15b4964-e296-4b50-8d2b-2de19b983126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Variable'])[1]/preceding::em[1]</value>
      <webElementGuid>b7316361-7905-41da-9b92-a032c15477a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Novedad Fecha'])[1]/preceding::em[2]</value>
      <webElementGuid>c93aa90b-f24d-4862-b8d3-38dd9dcf7d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/em</value>
      <webElementGuid>e9a8b947-630c-4c5d-91ae-95b30e80e8c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
