<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Filtrar por Actos Administrativos_form_ActosAdministrativostabla_principal_actosj_idt115filter</name>
   <tag></tag>
   <elementGuidId>d6827844-5a39-464c-b40c-ae00797de908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[2]/input</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87fabc2d-97d1-4e5c-a1ce-b7314da14366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_ActosAdministrativos:tabla_principal_actos:j_idt115:filter</value>
      <webElementGuid>66226fce-6b0c-4aa1-ac4c-f4f5f2ee7118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_ActosAdministrativos:tabla_principal_actos:j_idt115:filter</value>
      <webElementGuid>cab7c80e-8076-42a9-a1f7-2d09d6215f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-column-filter ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-hover ui-state-focus</value>
      <webElementGuid>654ba99e-86aa-4b48-be60-9dcb51a08706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>afbcfe2e-549e-4cf6-a8b0-4fd2048cf9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>form_ActosAdministrativos:tabla_principal_actos:j_idt115:filter_label</value>
      <webElementGuid>a07cfcdf-f121-4511-bbea-0b46beb8e479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>412b21ca-0723-492c-bb5e-55ea92101e73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>64c4b457-bedc-4fd1-aad1-d1b5948b8a00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>94190af3-0a7c-47be-9ca1-ee918d0f06c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_ActosAdministrativos:tabla_principal_actos:j_idt115:filter&quot;)</value>
      <webElementGuid>7d369cce-8be9-4ded-b557-6cf95cfb8fc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_ActosAdministrativos:tabla_principal_actos:j_idt115:filter']</value>
      <webElementGuid>5774d24a-a996-4a64-8058-56e45240fa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='form_ActosAdministrativos:tabla_principal_actos:j_idt115']/input</value>
      <webElementGuid>c94a2630-3284-4bbe-bc0e-0a8cf0e5fb2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/input</value>
      <webElementGuid>f530b9ce-3a8a-4224-8abe-9cf6e401bfd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_ActosAdministrativos:tabla_principal_actos:j_idt115:filter' and @name = 'form_ActosAdministrativos:tabla_principal_actos:j_idt115:filter']</value>
      <webElementGuid>a1f3b65e-119e-4d06-ab44-dbea22c81923</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
