<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Seleccione--EmpleadoPuestoUnidad Organizacional</name>
   <tag></tag>
   <elementGuidId>ff4f929c-bf78-47f7-af3c-d958b54e2c73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dfe85664-d56c-4f82-8bc1-f73571841f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popupBusquedaPlanta:sel</value>
      <webElementGuid>86fbc52f-739f-4500-a6c5-c434cb1584ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popupBusquedaPlanta:sel</value>
      <webElementGuid>ef75a0e0-92c5-4f08-ad3f-97eb815e696d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>valor_campo_estandar</value>
      <webElementGuid>2bf94f1a-7875-4412-903a-6f0eb6e2f332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>42aad135-1faf-4612-a0bf-6ecee86a6ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;valueChange&quot;,f:&quot;popupBusquedaPlanta&quot;,p:&quot;popupBusquedaPlanta:sel&quot;,u:&quot;popupBusquedaPlanta&quot;});</value>
      <webElementGuid>0a4b9c68-8d28-449e-bb80-44e07250a246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	--Seleccione--
	Empleado
	Puesto
	Unidad Organizacional
</value>
      <webElementGuid>f77f485f-03e4-4c97-b3da-d4ad0e8a6236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupBusquedaPlanta:sel&quot;)</value>
      <webElementGuid>3b2b3f66-3394-412d-8a3e-defd0c1f72c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='popupBusquedaPlanta:sel']</value>
      <webElementGuid>cc4aa3c9-148f-4f2d-9a20-a607fb66cbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='popupBusquedaPlanta:busqueda']/tbody/tr/td[2]/select</value>
      <webElementGuid>0ddf55ab-461c-4e99-86f8-d500e8c5ee11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Búsqueda'])[1]/following::select[1]</value>
      <webElementGuid>795bc9a4-ceae-4044-9dc7-ead88740cff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::select[1]</value>
      <webElementGuid>5234eac3-002d-43a8-82da-d2870d4314dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::select[1]</value>
      <webElementGuid>41d185db-d238-4b01-a9ea-a20f5f895156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>30369b70-1e78-4c24-beec-25c730ae36ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'popupBusquedaPlanta:sel' and @name = 'popupBusquedaPlanta:sel' and (text() = '	--Seleccione--
	Empleado
	Puesto
	Unidad Organizacional
' or . = '	--Seleccione--
	Empleado
	Puesto
	Unidad Organizacional
')]</value>
      <webElementGuid>44a877b1-26f2-4262-a6d7-10bc7a7b2f81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
