<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Legalizar</name>
   <tag></tag>
   <elementGuidId>d986b37a-fe26-4008-a598-86aa033dc6f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]/td/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bed767da-3378-444c-8a08-0a7186365199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-accion-acto</value>
      <webElementGuid>dbf85e74-1c4c-45bc-aeac-c6f92ff98f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Legalizar</value>
      <webElementGuid>c818dd3a-721b-47bc-ba65-1de9b3fde958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_ActosAdministrativos:tabla_principal_1:2:j_idt81&quot;)/span[@class=&quot;label-accion-acto&quot;]</value>
      <webElementGuid>73a3ecee-cbd9-4ef9-b1ac-3240d8356b82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='form_ActosAdministrativos:tabla_principal_1:2:j_idt81']/span</value>
      <webElementGuid>bd858cd3-5c83-4739-af46-23cf5434e49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Eliminar'])[1]/following::span[1]</value>
      <webElementGuid>55b8f7e0-a167-40a0-9994-1067dabc6958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elaborar'])[1]/following::span[2]</value>
      <webElementGuid>e51382ec-22ed-4923-b51e-5b3ae0747516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modificar'])[1]/preceding::span[1]</value>
      <webElementGuid>90cf6765-b20a-4901-b8fe-fe466a34ff92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Legalizar'])[2]/preceding::span[2]</value>
      <webElementGuid>e74f39d8-0c94-4d63-818a-95609d34bf00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Legalizar']/parent::*</value>
      <webElementGuid>167c82c9-e83a-4cc5-9d6c-dbce4baba368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/a[2]/span</value>
      <webElementGuid>e6da25de-9066-4f3e-b604-73b963228edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Legalizar' or . = 'Legalizar')]</value>
      <webElementGuid>f15456b3-7528-41a1-b9cc-0a11631e4a5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
