<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Unidad Solicita_form_detalleviaticosj_idt1299</name>
   <tag></tag>
   <elementGuidId>9de889a4-581b-4db5-a92d-3fde66916e8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form_detalleviaticos:contenido_tabla']/table/tbody/tr[1]/td/table/tbody/tr[1]/td/table/tbody/tr[9]/td[2]/table/tbody/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>12f01a2c-5e5c-4ee1-ad85-29d4eaf2089b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_detalleviaticos:j_idt1299</value>
      <webElementGuid>7670739f-bee8-409e-bec1-3573c5633ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>88a0c88d-a1e7-404e-b2e0-97bc06a5345b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget btn_popupInformacion</value>
      <webElementGuid>54359b60-2ef8-4f51-a367-b244236b5bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_detalleviaticos:j_idt1299&quot;,f:&quot;form_detalleviaticos&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>803ca6a8-fb37-4208-9a46-327e18ca4c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_detalleviaticos:j_idt1299&quot;)</value>
      <webElementGuid>0a557273-3069-4e3f-83df-5c4662789717</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='form_detalleviaticos:j_idt1299']</value>
      <webElementGuid>1713a214-5851-4521-af7d-b104a03bd8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_detalleviaticos:contenido_tabla']/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr[8]/td[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>1cfd2078-a777-4c5c-a83c-6d6b9716fd0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[26]</value>
      <webElementGuid>4dca5a5f-ad6e-4a20-9e49-5d7143447de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/table/tbody/tr/td[2]/a</value>
      <webElementGuid>670a8993-977d-4555-abe4-feb7857f0a02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
