<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Concepto</name>
   <tag></tag>
   <elementGuidId>8a53edba-7bf4-45d9-b804-d92dfb54c5c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[4]/div/table/tbody/tr[4]/td/table/tbody/tr/td/form/div/div[2]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f225b505-85bc-4c05-b72f-4884f8794b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Concepto</value>
      <webElementGuid>fecdce7a-ef2a-40cc-b1aa-cb1b2036e59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;conceptoempleado_form:j_idt411_content&quot;)/div[@class=&quot;us-head-popup us-popup-img&quot;]/label[1]</value>
      <webElementGuid>76c43401-a2d6-4940-8b38-d3c0bd8a5372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='conceptoempleado_form:j_idt411_content']/div/label</value>
      <webElementGuid>b2a3ea9d-5d81-4f56-ba59-64dd0315eab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Costo Incurre*'])[1]/following::label[1]</value>
      <webElementGuid>26292f64-c4af-4c59-8a73-ea20120e14d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Hasta'])[1]/following::label[1]</value>
      <webElementGuid>09b7fdf4-733f-4933-ba60-f6afc049b9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Concepto*'])[1]/preceding::label[1]</value>
      <webElementGuid>b4bf744d-a8ea-4914-9db5-015238afecdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vigencia*'])[1]/preceding::label[1]</value>
      <webElementGuid>ea43e061-3f1e-43ba-8ec5-402bde126c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[9]/div/div[2]/div/label</value>
      <webElementGuid>632c58fd-b62c-4016-b49f-8b34d5f2132f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Concepto' or . = 'Concepto')]</value>
      <webElementGuid>001543d8-6ecb-43ba-a9d7-a5ef91e6801f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
