<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Generar1</name>
   <tag></tag>
   <elementGuidId>51189a70-b5cd-412e-ad2d-5f269bb3b62b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[3]/tbody/tr/td[1]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a7322365-1b64-4517-b2c8-3496be02f20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipoPeriodo:panelTabInformacion:j_idt103</value>
      <webElementGuid>22c77898-4d00-410d-8769-75a062e6abda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>679defc2-f64d-4ea1-9fd4-fd3b4239cdc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton btn-generar</value>
      <webElementGuid>5fe336f6-4260-4ad0-bd69-7136b3135dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;tipoPeriodo:panelTabInformacion:j_idt103&quot;,f:&quot;tipoPeriodo&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>2c4f552f-dbc8-49c6-a791-5ab558e39c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generar</value>
      <webElementGuid>d1cf9aa3-bb88-42af-8b8e-2143c2760911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipoPeriodo:panelTabInformacion:j_idt103&quot;)</value>
      <webElementGuid>232318a7-de8e-459d-88a6-44df1b4c3877</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tipoPeriodo:panelTabInformacion:j_idt103']</value>
      <webElementGuid>00db731d-10df-4dd4-b5a7-409498b536e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tipoPeriodo:panelTabInformacion:j_idt74']/table[2]/tbody/tr/td[2]/a</value>
      <webElementGuid>c3e803d7-1db8-4ad9-9e67-ce1805f54e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Generar')]</value>
      <webElementGuid>cb5f5510-dffb-43c6-898b-99e7469be9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Causado'])[10]/following::a[2]</value>
      <webElementGuid>a2b44ac6-48a6-4914-ad77-ab2b52bf10c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periodo Abonado'])[1]/following::a[2]</value>
      <webElementGuid>60eda3d2-0a45-4b27-bb0a-11d32516020e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Definición Ciclo'])[1]/preceding::a[3]</value>
      <webElementGuid>49fb0c73-0ea6-40e8-9e0a-f58d5e8973e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Generar']/parent::*</value>
      <webElementGuid>73508bca-3d45-461c-80b8-5e1396d252bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[30]</value>
      <webElementGuid>63d2aa0f-1e2f-4634-9496-31d124295c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/a</value>
      <webElementGuid>f802a0a2-68e4-422c-beb8-172ef25aeed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'tipoPeriodo:panelTabInformacion:j_idt103' and @href = '#' and (text() = 'Generar' or . = 'Generar')]</value>
      <webElementGuid>28c08272-f0c3-4af0-8c20-47c6de07a0b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
