<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Generacion Entidad Pago (com)</name>
   <tag></tag>
   <elementGuidId>dc1bf8e7-2b40-4d32-9a19-18359201a902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ui-autocomplete-item.ui-autocomplete-list-item.ui-corner-all.ui-state-highlight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2790621f-2bdb-4265-8315-9b8430473280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-autocomplete-item ui-autocomplete-list-item ui-corner-all ui-state-highlight</value>
      <webElementGuid>761af244-eb52-43cc-8e98-e90bdc1824af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-label</name>
      <type>Main</type>
      <value>Generacion Entidad Pago (com)</value>
      <webElementGuid>2d414c5a-ec2e-4d2c-9eef-feac87efc6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-value</name>
      <type>Main</type>
      <value>Generacion Entidad Pago (com)</value>
      <webElementGuid>678e3235-acc9-426a-8d9e-6e1020af8418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e42248f9-0cf4-4bea-ae61-38559affe5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Generacion Entidad Pago (com)</value>
      <webElementGuid>e96e3286-bc7c-45e3-8e46-1e144e461ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_template:j_idt24_panel&quot;)/ul[@class=&quot;ui-autocomplete-items ui-autocomplete-list ui-widget-content ui-widget ui-corner-all ui-helper-reset&quot;]/li[@class=&quot;ui-autocomplete-item ui-autocomplete-list-item ui-corner-all ui-state-highlight&quot;]</value>
      <webElementGuid>7d1b5646-7e54-4a07-ae79-5dbeca2e0966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='form_template:j_idt24_panel']/ul/li</value>
      <webElementGuid>d113dac4-337c-42b5-9e34-f39a40392afa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubicación Física'])[1]/following::li[1]</value>
      <webElementGuid>e750a940-018e-4b45-a493-52968d3fbacf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cargo'])[1]/following::li[1]</value>
      <webElementGuid>47d206a7-a214-4110-9d51-149c41d04bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='tidad Pago (com)']/parent::*</value>
      <webElementGuid>6344016a-0d7e-439a-8679-8ae81a6efa14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/ul/li</value>
      <webElementGuid>0c0e888f-db47-4dc5-a399-d8922a48f0c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Generacion Entidad Pago (com)' or . = 'Generacion Entidad Pago (com)')]</value>
      <webElementGuid>d7148891-65f3-4fba-bdcf-dd055b847e9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
