<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Acto cambio del Empleado_form_ActosAdministrativostabla_principal_10j_idt79</name>
   <tag></tag>
   <elementGuidId>255b8297-d942-4299-9212-4a6e41c57a1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/table/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98c101dd-c4ac-4871-8a8f-891f92e3b04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_ActosAdministrativos:tabla_principal_1:0:j_idt79</value>
      <webElementGuid>d02b2040-3918-4212-96df-d400a913f8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ab7e4592-fbe9-44d7-98d5-3f2919f33904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget glyphicons glyphicons-disk-save x2 us-gris</value>
      <webElementGuid>a3fa74af-bbf1-48e1-b982-c9e4e1878e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_ActosAdministrativos:tabla_principal_1:0:j_idt79&quot;,f:&quot;form_ActosAdministrativos&quot;,u:&quot;form_ActosAdministrativos&quot;,pa:[{name:&quot;estados&quot;,value:&quot;Elaborar&quot;}]});return false;</value>
      <webElementGuid>a25a9b6f-adf2-4ea3-a028-31d90906573f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_ActosAdministrativos:tabla_principal_1:0:j_idt79&quot;)</value>
      <webElementGuid>fb825c0c-1106-4231-9c66-9008bac5cd0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='form_ActosAdministrativos:tabla_principal_1:0:j_idt79']</value>
      <webElementGuid>4788b1c1-aeab-4dfb-88ca-9a1f19b0e436</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='form_ActosAdministrativos:tabla_principal_1_data']/tr/td/a</value>
      <webElementGuid>85615ae0-5a21-40ba-8b7a-2badb07a54dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[21]</value>
      <webElementGuid>a9659647-de22-4462-a9c3-21133d17e293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/table/tbody/tr/td/a</value>
      <webElementGuid>ac23f3df-fe51-41fe-af5b-22225fc7700f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'form_ActosAdministrativos:tabla_principal_1:0:j_idt79' and @href = '#']</value>
      <webElementGuid>ebdbb355-a0b5-4115-8671-d50283165e44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
