<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Empleados_form_ActosAdministrativosj_idt104</name>
   <tag></tag>
   <elementGuidId>d0041992-eef5-43ba-93e5-75f99178ed5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[2]/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64389cfc-8bf0-4d3f-9fc5-7868a88e50f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_ActosAdministrativos:j_idt104</value>
      <webElementGuid>ac599449-1922-413f-989b-132472c7f521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_ActosAdministrativos:j_idt104</value>
      <webElementGuid>9e690a64-12cb-4d04-9c6f-a7650d0b7383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8fc3faf2-9c2f-4c11-82e2-c03cb7cb080c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>cambio de sueldo</value>
      <webElementGuid>61fd9533-ccbd-44b1-a438-59abc93782a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ace_valor_campo_estandar ui-state-filled ui-state-hover ui-state-focus</value>
      <webElementGuid>988e584a-2b87-4857-868a-1b1f3b30cf6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a5a0524e-4a52-4d9c-888c-1bd74807b5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_ActosAdministrativos:j_idt104&quot;,e:&quot;valueChange&quot;,f:&quot;form_ActosAdministrativos&quot;,p:&quot;form_ActosAdministrativos:j_idt104&quot;,u:&quot;form_ActosAdministrativos:arbolFormato&quot;});</value>
      <webElementGuid>c604e74d-4281-4e59-af51-aabcc70e9d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>d8dd34f0-7ed9-4c09-b587-3cda98d3d2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f13e5273-d778-4d44-abad-e210f4a48b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee782fbc-d507-42b7-841a-289d08d97d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_ActosAdministrativos:j_idt104&quot;)</value>
      <webElementGuid>2ed8e790-7d59-4fef-ba74-73b23bca219b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_ActosAdministrativos:j_idt104']</value>
      <webElementGuid>57218ca1-e480-43c1-b888-4b557072e393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='form_ActosAdministrativos:contenido_tabla']/tbody/tr/td/table/tbody/tr[2]/td/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>b693f59b-9516-469e-b23b-189e52826c38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>6ecb4cc1-3e4e-4d46-93a6-13e9f41c05fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_ActosAdministrativos:j_idt104' and @name = 'form_ActosAdministrativos:j_idt104' and @type = 'text']</value>
      <webElementGuid>5ff9662d-3ea8-4685-b528-54d96a54eabf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
