<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__form_actosDirectosEmpleadoj_idt25342fecha_input</name>
   <tag></tag>
   <elementGuidId>3e745d49-89d3-4170-8db9-156a59fe9782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]/td[2]/table/tbody/tr/td/table/tbody/tr/td/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3ccb1fe-f8d3-4910-b9fd-a54605bbdcca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_actosDirectosEmpleado:j_idt2534:2:fecha_input</value>
      <webElementGuid>6e1f483c-b8bb-4fcf-b3c4-71da098b1a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form_actosDirectosEmpleado:j_idt2534:2:fecha_input</value>
      <webElementGuid>e1c49e5b-3717-46d1-a0c0-879d9eacf99b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74b538f5-d46a-4ed6-adba-051cb21c1ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-widget ui-state-default ui-corner-all hasDatepicker ui-state-hover ui-state-focus</value>
      <webElementGuid>8cabbc9e-454e-43fb-8698-38dee419daec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dab7f079-d627-4493-983e-f481d0c8b8cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>41d2434b-5079-4aeb-a6c9-1deeba5893ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>746a5749-1864-48b8-bff5-cf0fa9d3265b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e2b5ad98-2aa4-402f-a16d-2522c1996874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_actosDirectosEmpleado:j_idt2534:2:fecha_input&quot;)</value>
      <webElementGuid>1f2a41fe-a460-4cd3-9741-7c8d95c0e92d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form_actosDirectosEmpleado:j_idt2534:2:fecha_input']</value>
      <webElementGuid>7b0be61b-2b61-466e-9925-b7c15ffa210b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='form_actosDirectosEmpleado:j_idt2534:2:fecha']/input</value>
      <webElementGuid>a1e02506-82db-43c8-befb-3a9ae4301d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/table/tbody/tr/td/span/input</value>
      <webElementGuid>6250d745-9a59-4527-9a30-b3f9e211c515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form_actosDirectosEmpleado:j_idt2534:2:fecha_input' and @name = 'form_actosDirectosEmpleado:j_idt2534:2:fecha_input' and @type = 'text']</value>
      <webElementGuid>dbfbeefe-7187-496e-9559-27db9e41ae0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
