<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ReversarEliminar</name>
   <tag></tag>
   <elementGuidId>26e8ecf4-0781-47a2-b18b-3b03a96f8c4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Reversar/Eliminar')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>daa2ccb8-c79c-4d2a-9103-72b9d3e294b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form_liquidacionesPeriodicasEmpleado:tabLiquidacionesPeriodicas:j_idt3871</value>
      <webElementGuid>82b382d4-21d4-44d4-9588-8251ae991e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>eb222ce6-54e7-471b-a49b-07c840d1d683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget us-boton btn-eliminar</value>
      <webElementGuid>d248e3fa-a6f5-4198-99df-b5eef3526aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:&quot;form_liquidacionesPeriodicasEmpleado:tabLiquidacionesPeriodicas:j_idt3871&quot;,f:&quot;form_liquidacionesPeriodicasEmpleado&quot;,u:&quot;areaAplicacion&quot;});return false;</value>
      <webElementGuid>a779265d-dd9e-4327-b440-8f6c59eceeb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reversar/Eliminar</value>
      <webElementGuid>0bd3e281-7638-4950-87b8-ec4e79dbe2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_liquidacionesPeriodicasEmpleado:tabLiquidacionesPeriodicas:j_idt3871&quot;)</value>
      <webElementGuid>978489b1-7cf0-44ad-9194-6b62b18dab57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='form_liquidacionesPeriodicasEmpleado:tabLiquidacionesPeriodicas:j_idt3871']</value>
      <webElementGuid>f07d0e5d-42f3-4cab-9c2a-07d7426dbb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form_liquidacionesPeriodicasEmpleado:tabLiquidacionesPeriodicas:panelCamposFormulario']/div/table[6]/tbody/tr/td[2]/a</value>
      <webElementGuid>9c9c08f5-a1b5-46eb-8555-3750f2880af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Reversar/Eliminar')]</value>
      <webElementGuid>1f960c8f-401b-4262-a652-a298f853e6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seguimiento'])[1]/following::a[2]</value>
      <webElementGuid>6d5c9f6c-84b8-4655-b975-888ecbe9ef64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adjunto'])[1]/following::a[3]</value>
      <webElementGuid>098b0629-62e4-4bd1-8c08-c194b1ad23c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reporte'])[1]/preceding::a[2]</value>
      <webElementGuid>a4463619-ccd7-402c-adf3-fb24c758f8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recuperar Incapacidad'])[1]/preceding::a[6]</value>
      <webElementGuid>b1a74c1b-b1ce-463d-b6d4-013c1c49523e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reversar/Eliminar']/parent::*</value>
      <webElementGuid>b73851f5-bc9f-492d-8f81-4157bce89418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[54]</value>
      <webElementGuid>6f33824a-a344-49e1-9517-0fb7c7e2aebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[6]/tbody/tr/td[2]/a</value>
      <webElementGuid>ca9cb49d-b9b9-4041-854f-2ff69dabe83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'form_liquidacionesPeriodicasEmpleado:tabLiquidacionesPeriodicas:j_idt3871' and @href = '#' and (text() = 'Reversar/Eliminar' or . = 'Reversar/Eliminar')]</value>
      <webElementGuid>adcb13b4-36b6-43a4-ad24-e40e14b4c5d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
