<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contrato_LiquidacionNominaj_idt128</name>
   <tag></tag>
   <elementGuidId>1af137a2-d363-4835-aa80-7f5a8a425672</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/table/tbody/tr/td[4]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6593be14-be92-4fee-9844-0cb97827258f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LiquidacionNomina:j_idt128</value>
      <webElementGuid>cd8d7075-0549-4612-a119-e46b83e6dc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1a30adb-9f14-4a7f-bcb0-86f515786010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LiquidacionNomina:j_idt128</value>
      <webElementGuid>b9014d9c-60aa-4bd4-86c4-a4de6fcc3483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caja_texto</value>
      <webElementGuid>96dc03ed-2a4a-4986-8d92-1359bc5e7ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>dae05cf3-c81a-4a35-8875-0d5c997e5f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return entero(event);</value>
      <webElementGuid>38193a45-3203-4eeb-a8f7-5cdb4bbbc865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PrimeFaces.ab({s:this,e:&quot;valueChange&quot;,f:&quot;LiquidacionNomina&quot;,p:&quot;LiquidacionNomina:j_idt128&quot;,u:&quot;LiquidacionNomina:tabla_ln&quot;});</value>
      <webElementGuid>2cd8af6a-b937-47c9-aea0-cc82cc25c75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LiquidacionNomina:j_idt128&quot;)</value>
      <webElementGuid>c29c5f6b-3894-4da8-b862-b4464fc2154d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LiquidacionNomina:j_idt128']</value>
      <webElementGuid>9493ed65-3bb4-4b79-9cb2-287f4dd41c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='LiquidacionNomina:j_idt120_content']/table/tbody/tr/td[4]/input</value>
      <webElementGuid>ae6dd62f-c190-46a2-844e-f00285571312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[4]/input</value>
      <webElementGuid>203e3999-f153-4ab4-9aa9-20dd10297c90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LiquidacionNomina:j_idt128' and @type = 'text' and @name = 'LiquidacionNomina:j_idt128']</value>
      <webElementGuid>f58ff4a8-799c-4876-9a14-2509a9ac6376</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
