<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nombre_usuarioformatabnombre</name>
   <tag></tag>
   <elementGuidId>d51bcfa4-5a20-43a1-b927-a0b3c567400d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[3]/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0a5cc9b-569a-406e-8b06-14796827f4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usuarioforma:tab:nombre</value>
      <webElementGuid>ccc2b154-3ea2-4119-bba0-4ae6beb48b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>476f7ed1-6809-442a-8db3-cab5cb6d9575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>usuarioforma:tab:nombre</value>
      <webElementGuid>21cf6a41-20d9-42de-a507-47b538c27dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caja_texto</value>
      <webElementGuid>5ad0c6e1-a291-4bfa-93db-daeea66c2696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>af959853-e049-4706-bb44-5a3b0d171604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usuarioforma:tab:nombre&quot;)</value>
      <webElementGuid>5782447a-a8c7-48a2-9fbf-825edebf25c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usuarioforma:tab:nombre']</value>
      <webElementGuid>710f489c-6b31-4a19-86e6-104245189ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='usuarioforma:tab:j_idt87']/table/tbody/tr[3]/td[2]/input</value>
      <webElementGuid>849547a5-6abb-436d-ac92-eb4072b5c58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input</value>
      <webElementGuid>8efa05c0-044d-4123-891a-2e9801350acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'usuarioforma:tab:nombre' and @type = 'text' and @name = 'usuarioforma:tab:nombre']</value>
      <webElementGuid>15fa148c-1741-4449-88a1-d53a161e50f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
