<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Olvide Mi Clave</name>
   <tag></tag>
   <elementGuidId>5f7d24bf-9480-4133-99c4-4ac4a61ee065</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='Olvidé mi Clave']/parent::*</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.us-texto-recordar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>31a2eb7e-6097-4af6-a58d-58898626e2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>us-texto-recordar</value>
      <webElementGuid>aaa801e6-5f11-4d1e-b912-cfd10aa804d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Olvide Mi Clave</value>
      <webElementGuid>6812efb1-4dee-4256-b24e-51cc880f73f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/div[@class=&quot;us-container-login&quot;]/div[@class=&quot;us-caja-login&quot;]/div[3]/div[@class=&quot;us-ayuda&quot;]/a[1]/span[@class=&quot;us-texto-recordar&quot;]</value>
      <webElementGuid>a1163de6-d045-4c94-9f2f-941a64037366</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/div/div/div[3]/div[4]/a/span</value>
      <webElementGuid>000950d9-aba4-4308-a524-1418113fc4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recordar Clave'])[1]/preceding::span[3]</value>
      <webElementGuid>d8b7e3fe-c241-4f7f-b68a-913b5e80d666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingrese Login o Correo'])[1]/preceding::span[3]</value>
      <webElementGuid>2c72adb7-9e8d-49af-bd7a-812b114342ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Olvide Mi Clave']/parent::*</value>
      <webElementGuid>0f45ffbe-efc5-4632-acd7-87c694b011e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>10d44493-5d38-49f9-9ee5-275f8968a0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Olvide Mi Clave' or . = ' Olvide Mi Clave')]</value>
      <webElementGuid>5b68c99f-5711-434c-aa5b-fe96469e3ec2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
