<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Registro</name>
   <tag></tag>
   <elementGuidId>f9e9e2c2-0501-4789-ba73-a80f7fe3195b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[1]/div[4]/div/table/tbody/tr[3]/td/table/tbody/tr/td/div/table/tbody/tr/td[1]/form/table/tbody/tr[1]/td/div/div[8]/table[1]/tbody/tr/td/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b00e9c12-7e26-4f7a-8437-0d174aace6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>j_idt143:j_idt144:j_idt146:j_idt2292</value>
      <webElementGuid>acb1e4f3-8f79-4e8c-aacd-092fc9358aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>de0d0527-8b35-42de-9500-f2809210e230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-commandlink ui-widget</value>
      <webElementGuid>12560c64-2f58-4dbe-b76f-4f1901324568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PrimeFaces.addSubmitParam('j_idt143',{'j_idt143:j_idt144:j_idt146:j_idt2292':'j_idt143:j_idt144:j_idt146:j_idt2292'}).submit('j_idt143');return false;</value>
      <webElementGuid>1afa539a-348e-4c11-9f5c-9562e8cba335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registro    </value>
      <webElementGuid>3bd1303d-c44a-40ed-90ae-3abd2df67357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;j_idt143:j_idt144:j_idt146:j_idt2292&quot;)</value>
      <webElementGuid>a0e5a51b-c3a6-47d6-ac7a-76a29fe956de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='j_idt143:j_idt144:j_idt146:j_idt2292']</value>
      <webElementGuid>bae35a8a-d600-4328-ae08-c976f2b0d438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='j_idt143:j_idt144:j_idt146:j_idt2287']/table/tbody/tr/td/a</value>
      <webElementGuid>6809c696-50b4-487d-bf65-8601d7b7e05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Registro')])[4]</value>
      <webElementGuid>91f0c81c-dc09-45ee-a3bf-f8f86abb5aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Costo'])[1]/following::a[1]</value>
      <webElementGuid>33059184-105c-437b-adc7-dbbf15708ed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recursos'])[1]/following::a[2]</value>
      <webElementGuid>aee24f73-8667-4b67-8c33-b7c0061b098d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Programación'])[1]/preceding::a[2]</value>
      <webElementGuid>029c25ae-e263-4bb7-afd3-f5e364782784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Evaluación'])[1]/preceding::a[6]</value>
      <webElementGuid>ec6b5a49-b7cb-4410-9a56-e7cf4e07e211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[39]</value>
      <webElementGuid>cfd77cb6-9948-4a4d-9df3-3ebe780d23ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/table/tbody/tr/td/a</value>
      <webElementGuid>d4ebc4bd-f853-4279-a036-a23398af0a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
